// <auto-generated />
using System;
using EmployeeMangement.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMangement.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20220128215456_EmployeeCreate")]
    partial class EmployeeCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeMangement.Models.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bosses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Adrian",
                            LastName = "Tremblay"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Raleigh",
                            LastName = "Altenwerth"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Ferne",
                            LastName = "Hagenes"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Geraldine",
                            LastName = "Runolfsdottir"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Frieda",
                            LastName = "Rowe"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BossId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1975, 1, 28, 23, 54, 56, 144, DateTimeKind.Local).AddTicks(6007),
                            BossId = 3,
                            EmploymentDate = new DateTime(2004, 1, 28, 23, 54, 56, 144, DateTimeKind.Local).AddTicks(6917),
                            FirstName = "Brisa",
                            HomeAddress = "212 Blick Corners",
                            LastName = "Windler",
                            RoleId = 2,
                            Salary = 2799
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2004, 1, 28, 23, 54, 56, 144, DateTimeKind.Local).AddTicks(9438),
                            BossId = 1,
                            EmploymentDate = new DateTime(2016, 1, 28, 23, 54, 56, 144, DateTimeKind.Local).AddTicks(9465),
                            FirstName = "Jeanette",
                            HomeAddress = "83318 Mario Points",
                            LastName = "Keeling",
                            RoleId = 5,
                            Salary = 2553
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1990, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(1399),
                            BossId = 3,
                            EmploymentDate = new DateTime(2002, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(1410),
                            FirstName = "Leonie",
                            HomeAddress = "9241 Lacey Station",
                            LastName = "Ritchie",
                            RoleId = 2,
                            Salary = 2584
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1987, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(2853),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(2862),
                            FirstName = "Karine",
                            HomeAddress = "26245 Raynor Port",
                            LastName = "Daniel",
                            RoleId = 4,
                            Salary = 2721
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(2000, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(5395),
                            BossId = 3,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(5405),
                            FirstName = "Granville",
                            HomeAddress = "521 Cathrine Ferry",
                            LastName = "McLaughlin",
                            RoleId = 2,
                            Salary = 1013
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1994, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(7006),
                            BossId = 4,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(7016),
                            FirstName = "Freida",
                            HomeAddress = "19845 Yost Union",
                            LastName = "Russel",
                            RoleId = 2,
                            Salary = 1412
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1972, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(8593),
                            BossId = 3,
                            EmploymentDate = new DateTime(2014, 1, 28, 23, 54, 56, 145, DateTimeKind.Local).AddTicks(8603),
                            FirstName = "Antoinette",
                            HomeAddress = "178 Zieme Light",
                            LastName = "Mosciski",
                            RoleId = 2,
                            Salary = 2674
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1966, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(759),
                            BossId = 5,
                            EmploymentDate = new DateTime(2012, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(768),
                            FirstName = "Dominique",
                            HomeAddress = "25401 Retha Walks",
                            LastName = "Johnson",
                            RoleId = 3,
                            Salary = 1718
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1984, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(2848),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(2858),
                            FirstName = "Ruby",
                            HomeAddress = "170 Leonardo Street",
                            LastName = "Hermiston",
                            RoleId = 5,
                            Salary = 1050
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1959, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(5002),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(5012),
                            FirstName = "Tobin",
                            HomeAddress = "2896 Carleton Islands",
                            LastName = "Morar",
                            RoleId = 3,
                            Salary = 2044
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1979, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(7081),
                            BossId = 2,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(7091),
                            FirstName = "Paolo",
                            HomeAddress = "88514 Yazmin Ways",
                            LastName = "Zemlak",
                            RoleId = 4,
                            Salary = 2735
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1975, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(8325),
                            BossId = 1,
                            EmploymentDate = new DateTime(2016, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(8335),
                            FirstName = "Maryam",
                            HomeAddress = "28734 Kub Rest",
                            LastName = "Armstrong",
                            RoleId = 3,
                            Salary = 1808
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1969, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(9535),
                            BossId = 2,
                            EmploymentDate = new DateTime(2018, 1, 28, 23, 54, 56, 146, DateTimeKind.Local).AddTicks(9545),
                            FirstName = "Don",
                            HomeAddress = "5002 Jewess Mountain",
                            LastName = "Mueller",
                            RoleId = 2,
                            Salary = 2587
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1988, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(1410),
                            BossId = 5,
                            EmploymentDate = new DateTime(2006, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(1420),
                            FirstName = "Polly",
                            HomeAddress = "839 Kaycee Harbor",
                            LastName = "Erdman",
                            RoleId = 1,
                            Salary = 1173
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1996, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(2652),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(2662),
                            FirstName = "Kiarra",
                            HomeAddress = "9707 Douglas Green",
                            LastName = "Lind",
                            RoleId = 4,
                            Salary = 1556
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(2001, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(3846),
                            BossId = 3,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(3855),
                            FirstName = "Amelia",
                            HomeAddress = "3940 Daugherty Fort",
                            LastName = "Glover",
                            RoleId = 1,
                            Salary = 1731
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1994, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(5435),
                            BossId = 3,
                            EmploymentDate = new DateTime(2007, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(5466),
                            FirstName = "Tyson",
                            HomeAddress = "527 Conroy Loop",
                            LastName = "Kulas",
                            RoleId = 5,
                            Salary = 2443
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1967, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(6997),
                            BossId = 2,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(7009),
                            FirstName = "Erwin",
                            HomeAddress = "673 Kunze Mission",
                            LastName = "Mosciski",
                            RoleId = 1,
                            Salary = 1701
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1976, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(9311),
                            BossId = 3,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 147, DateTimeKind.Local).AddTicks(9323),
                            FirstName = "Reilly",
                            HomeAddress = "85819 Max Crescent",
                            LastName = "Ritchie",
                            RoleId = 2,
                            Salary = 1600
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1966, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(1567),
                            BossId = 5,
                            EmploymentDate = new DateTime(2002, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(1579),
                            FirstName = "Adolfo",
                            HomeAddress = "696 Eladio Haven",
                            LastName = "Toy",
                            RoleId = 2,
                            Salary = 2032
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1998, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(3767),
                            BossId = 3,
                            EmploymentDate = new DateTime(2016, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(3780),
                            FirstName = "Napoleon",
                            HomeAddress = "11249 Fabian Streets",
                            LastName = "Treutel",
                            RoleId = 3,
                            Salary = 1664
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1958, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(5682),
                            BossId = 1,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(5691),
                            FirstName = "Kiarra",
                            HomeAddress = "524 Marisa Underpass",
                            LastName = "Auer",
                            RoleId = 1,
                            Salary = 1904
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1969, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(6836),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(6845),
                            FirstName = "Araceli",
                            HomeAddress = "34455 Zboncak Roads",
                            LastName = "Kunze",
                            RoleId = 1,
                            Salary = 1310
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1978, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(8655),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 148, DateTimeKind.Local).AddTicks(8664),
                            FirstName = "Samara",
                            HomeAddress = "5777 Braeden Causeway",
                            LastName = "Wunsch",
                            RoleId = 1,
                            Salary = 2610
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1970, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(458),
                            BossId = 2,
                            EmploymentDate = new DateTime(2002, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(467),
                            FirstName = "Ezequiel",
                            HomeAddress = "4720 Arturo Fall",
                            LastName = "Hane",
                            RoleId = 4,
                            Salary = 2651
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1981, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(2248),
                            BossId = 5,
                            EmploymentDate = new DateTime(2005, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(2257),
                            FirstName = "Santiago",
                            HomeAddress = "9281 Mohammad Motorway",
                            LastName = "Schaefer",
                            RoleId = 4,
                            Salary = 1920
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(1982, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(3403),
                            BossId = 4,
                            EmploymentDate = new DateTime(2008, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(3412),
                            FirstName = "Marques",
                            HomeAddress = "807 Schultz Passage",
                            LastName = "Kuvalis",
                            RoleId = 5,
                            Salary = 2517
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1990, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(4596),
                            BossId = 1,
                            EmploymentDate = new DateTime(2019, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(4606),
                            FirstName = "Ethyl",
                            HomeAddress = "852 Bergstrom Drives",
                            LastName = "Hermann",
                            RoleId = 5,
                            Salary = 1731
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1991, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(5729),
                            BossId = 3,
                            EmploymentDate = new DateTime(2006, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(5738),
                            FirstName = "Cornell",
                            HomeAddress = "73085 Graham Landing",
                            LastName = "Wolf",
                            RoleId = 3,
                            Salary = 1686
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1974, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(7485),
                            BossId = 1,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(7494),
                            FirstName = "Modesto",
                            HomeAddress = "052 Joel Fords",
                            LastName = "Emard",
                            RoleId = 2,
                            Salary = 1539
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1972, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(9283),
                            BossId = 3,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 149, DateTimeKind.Local).AddTicks(9292),
                            FirstName = "Brennan",
                            HomeAddress = "47599 Amely Summit",
                            LastName = "Langworth",
                            RoleId = 5,
                            Salary = 2454
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(1968, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(418),
                            BossId = 2,
                            EmploymentDate = new DateTime(2018, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(427),
                            FirstName = "Aisha",
                            HomeAddress = "36310 Bode Square",
                            LastName = "Bernhard",
                            RoleId = 5,
                            Salary = 1403
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(1979, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(1562),
                            BossId = 1,
                            EmploymentDate = new DateTime(2009, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(1571),
                            FirstName = "Alexandrine",
                            HomeAddress = "546 Ryan Stream",
                            LastName = "Armstrong",
                            RoleId = 4,
                            Salary = 2171
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(1987, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(3340),
                            BossId = 3,
                            EmploymentDate = new DateTime(2003, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(3349),
                            FirstName = "Dominique",
                            HomeAddress = "847 Chet Port",
                            LastName = "Armstrong",
                            RoleId = 3,
                            Salary = 2283
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1971, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(5233),
                            BossId = 5,
                            EmploymentDate = new DateTime(2008, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(5251),
                            FirstName = "Jamil",
                            HomeAddress = "008 Ethel Rue",
                            LastName = "Swaniawski",
                            RoleId = 2,
                            Salary = 2621
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1958, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(7091),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(7100),
                            FirstName = "Katrina",
                            HomeAddress = "46156 Nikolas Lock",
                            LastName = "Wehner",
                            RoleId = 5,
                            Salary = 2568
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1970, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(8878),
                            BossId = 4,
                            EmploymentDate = new DateTime(2002, 1, 28, 23, 54, 56, 150, DateTimeKind.Local).AddTicks(8888),
                            FirstName = "Anahi",
                            HomeAddress = "2746 Leda Courts",
                            LastName = "Feil",
                            RoleId = 3,
                            Salary = 1410
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1978, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(25),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(34),
                            FirstName = "Prince",
                            HomeAddress = "74851 Turcotte Spur",
                            LastName = "Mann",
                            RoleId = 2,
                            Salary = 2783
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1978, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(1833),
                            BossId = 1,
                            EmploymentDate = new DateTime(2019, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(1842),
                            FirstName = "Marjolaine",
                            HomeAddress = "1838 Else Branch",
                            LastName = "Harber",
                            RoleId = 3,
                            Salary = 2616
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1974, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(3618),
                            BossId = 1,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(3627),
                            FirstName = "Myra",
                            HomeAddress = "84606 Randall Expressway",
                            LastName = "Ritchie",
                            RoleId = 2,
                            Salary = 2876
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1969, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(5429),
                            BossId = 4,
                            EmploymentDate = new DateTime(2003, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(5438),
                            FirstName = "Blake",
                            HomeAddress = "25294 Barrett Gardens",
                            LastName = "Gerlach",
                            RoleId = 2,
                            Salary = 1496
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(2000, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(6584),
                            BossId = 2,
                            EmploymentDate = new DateTime(2017, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(6594),
                            FirstName = "Justyn",
                            HomeAddress = "382 Kunze Summit",
                            LastName = "Flatley",
                            RoleId = 1,
                            Salary = 2664
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(1982, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(7770),
                            BossId = 3,
                            EmploymentDate = new DateTime(2017, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(7779),
                            FirstName = "Toy",
                            HomeAddress = "5840 Block Manors",
                            LastName = "Orn",
                            RoleId = 3,
                            Salary = 1714
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1996, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(8919),
                            BossId = 4,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 151, DateTimeKind.Local).AddTicks(8929),
                            FirstName = "Luella",
                            HomeAddress = "743 Toy Mill",
                            LastName = "Gusikowski",
                            RoleId = 2,
                            Salary = 2095
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1982, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(717),
                            BossId = 4,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(725),
                            FirstName = "Kristofer",
                            HomeAddress = "267 Natasha Ridge",
                            LastName = "Hackett",
                            RoleId = 4,
                            Salary = 1650
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(1962, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(2507),
                            BossId = 2,
                            EmploymentDate = new DateTime(2004, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(2517),
                            FirstName = "Peyton",
                            HomeAddress = "56431 Kallie Course",
                            LastName = "Strosin",
                            RoleId = 5,
                            Salary = 1157
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1956, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(3700),
                            BossId = 3,
                            EmploymentDate = new DateTime(2008, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(3710),
                            FirstName = "Reggie",
                            HomeAddress = "99150 Senger Island",
                            LastName = "Walker",
                            RoleId = 2,
                            Salary = 2535
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1988, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(4884),
                            BossId = 2,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(4894),
                            FirstName = "Ronaldo",
                            HomeAddress = "92005 Kunde Brooks",
                            LastName = "Gutkowski",
                            RoleId = 2,
                            Salary = 1750
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(1973, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(6694),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(6704),
                            FirstName = "Adrienne",
                            HomeAddress = "293 Brandt Creek",
                            LastName = "Treutel",
                            RoleId = 5,
                            Salary = 2099
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(1956, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(7854),
                            BossId = 1,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(7863),
                            FirstName = "Trenton",
                            HomeAddress = "7866 Von Meadow",
                            LastName = "Macejkovic",
                            RoleId = 2,
                            Salary = 1190
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(1990, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(9667),
                            BossId = 4,
                            EmploymentDate = new DateTime(2009, 1, 28, 23, 54, 56, 152, DateTimeKind.Local).AddTicks(9676),
                            FirstName = "Camron",
                            HomeAddress = "2323 Margaret Hollow",
                            LastName = "Effertz",
                            RoleId = 4,
                            Salary = 2053
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(1963, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(1472),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(1481),
                            FirstName = "Bria",
                            HomeAddress = "73000 Francesco Parkway",
                            LastName = "McClure",
                            RoleId = 5,
                            Salary = 2012
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(2003, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(2648),
                            BossId = 5,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(2657),
                            FirstName = "Jack",
                            HomeAddress = "00418 Witting Springs",
                            LastName = "Cummings",
                            RoleId = 1,
                            Salary = 1878
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(1997, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(3837),
                            BossId = 1,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(3847),
                            FirstName = "Hilton",
                            HomeAddress = "0749 Kub Brooks",
                            LastName = "Kassulke",
                            RoleId = 5,
                            Salary = 2134
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(1997, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(5651),
                            BossId = 5,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(5660),
                            FirstName = "Magnolia",
                            HomeAddress = "16803 Rodger Trace",
                            LastName = "Bernhard",
                            RoleId = 4,
                            Salary = 2117
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(1971, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(6805),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(6815),
                            FirstName = "Margarette",
                            HomeAddress = "818 Zemlak Stream",
                            LastName = "Kilback",
                            RoleId = 3,
                            Salary = 2430
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(1997, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(7986),
                            BossId = 2,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(7995),
                            FirstName = "Esperanza",
                            HomeAddress = "4331 Bernier Mount",
                            LastName = "Lemke",
                            RoleId = 1,
                            Salary = 2626
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(1984, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(9140),
                            BossId = 2,
                            EmploymentDate = new DateTime(2006, 1, 28, 23, 54, 56, 153, DateTimeKind.Local).AddTicks(9149),
                            FirstName = "Hortense",
                            HomeAddress = "89111 Heaney Radial",
                            LastName = "Rolfson",
                            RoleId = 3,
                            Salary = 2223
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(1979, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(960),
                            BossId = 3,
                            EmploymentDate = new DateTime(2012, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(970),
                            FirstName = "Ashton",
                            HomeAddress = "4806 Ariel Trail",
                            LastName = "Koch",
                            RoleId = 2,
                            Salary = 2816
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(1965, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(2776),
                            BossId = 1,
                            EmploymentDate = new DateTime(2018, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(2785),
                            FirstName = "Jeanne",
                            HomeAddress = "270 Zola Ferry",
                            LastName = "Weimann",
                            RoleId = 3,
                            Salary = 1612
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(1981, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(3950),
                            BossId = 3,
                            EmploymentDate = new DateTime(2005, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(3959),
                            FirstName = "Ramon",
                            HomeAddress = "524 Kuhic Forges",
                            LastName = "Cronin",
                            RoleId = 5,
                            Salary = 1315
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(1980, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(5120),
                            BossId = 2,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(5129),
                            FirstName = "Amina",
                            HomeAddress = "8028 Ward Turnpike",
                            LastName = "King",
                            RoleId = 2,
                            Salary = 1017
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(1960, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(6300),
                            BossId = 5,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(6309),
                            FirstName = "Jakayla",
                            HomeAddress = "9605 Jerde Dale",
                            LastName = "Predovic",
                            RoleId = 2,
                            Salary = 2507
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(1956, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(7479),
                            BossId = 2,
                            EmploymentDate = new DateTime(2022, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(7488),
                            FirstName = "Isabel",
                            HomeAddress = "09412 Effertz Dale",
                            LastName = "Parker",
                            RoleId = 1,
                            Salary = 1124
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(1972, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(8633),
                            BossId = 2,
                            EmploymentDate = new DateTime(2001, 1, 28, 23, 54, 56, 154, DateTimeKind.Local).AddTicks(8642),
                            FirstName = "Annamarie",
                            HomeAddress = "3433 Ruecker Rapid",
                            LastName = "Shields",
                            RoleId = 4,
                            Salary = 1433
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(1975, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(445),
                            BossId = 2,
                            EmploymentDate = new DateTime(2005, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(454),
                            FirstName = "Kelvin",
                            HomeAddress = "973 Brice Skyway",
                            LastName = "Bins",
                            RoleId = 4,
                            Salary = 1254
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(1993, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(2254),
                            BossId = 5,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(2263),
                            FirstName = "Okey",
                            HomeAddress = "55146 Nestor Glens",
                            LastName = "Connelly",
                            RoleId = 4,
                            Salary = 2567
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(1964, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(4359),
                            BossId = 5,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(4368),
                            FirstName = "Gianni",
                            HomeAddress = "466 Beaulah Loaf",
                            LastName = "Marvin",
                            RoleId = 2,
                            Salary = 1704
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(2001, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(5550),
                            BossId = 5,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(5559),
                            FirstName = "Jace",
                            HomeAddress = "135 Wisozk Station",
                            LastName = "Bechtelar",
                            RoleId = 3,
                            Salary = 2310
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(1993, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(7357),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(7367),
                            FirstName = "Brooklyn",
                            HomeAddress = "11177 Krystel Throughway",
                            LastName = "Schuster",
                            RoleId = 1,
                            Salary = 1283
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(1998, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(8551),
                            BossId = 3,
                            EmploymentDate = new DateTime(2008, 1, 28, 23, 54, 56, 155, DateTimeKind.Local).AddTicks(8578),
                            FirstName = "Ethelyn",
                            HomeAddress = "07265 Kovacek Ports",
                            LastName = "Watsica",
                            RoleId = 1,
                            Salary = 2462
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(1984, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(708),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(717),
                            FirstName = "Tyler",
                            HomeAddress = "4247 Josefina Road",
                            LastName = "Hyatt",
                            RoleId = 1,
                            Salary = 2093
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(1956, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(3163),
                            BossId = 5,
                            EmploymentDate = new DateTime(2007, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(3173),
                            FirstName = "Martin",
                            HomeAddress = "95418 Justyn Turnpike",
                            LastName = "Kozey",
                            RoleId = 5,
                            Salary = 2639
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(1969, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(4711),
                            BossId = 1,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(4721),
                            FirstName = "Ruthie",
                            HomeAddress = "75115 Hermiston Keys",
                            LastName = "Gusikowski",
                            RoleId = 4,
                            Salary = 2267
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(1991, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(6329),
                            BossId = 4,
                            EmploymentDate = new DateTime(2010, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(6338),
                            FirstName = "Wilhelmine",
                            HomeAddress = "57009 Larkin Unions",
                            LastName = "Hickle",
                            RoleId = 3,
                            Salary = 1063
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(2001, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(8301),
                            BossId = 5,
                            EmploymentDate = new DateTime(2019, 1, 28, 23, 54, 56, 156, DateTimeKind.Local).AddTicks(8311),
                            FirstName = "Zella",
                            HomeAddress = "196 Preston Union",
                            LastName = "Turcotte",
                            RoleId = 3,
                            Salary = 2646
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(1955, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(416),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(425),
                            FirstName = "Cydney",
                            HomeAddress = "0006 Chesley Shores",
                            LastName = "Padberg",
                            RoleId = 3,
                            Salary = 1587
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(1972, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(2470),
                            BossId = 3,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(2479),
                            FirstName = "Jaqueline",
                            HomeAddress = "24178 Felipe Expressway",
                            LastName = "McKenzie",
                            RoleId = 1,
                            Salary = 2988
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(1998, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(3842),
                            BossId = 4,
                            EmploymentDate = new DateTime(2006, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(3851),
                            FirstName = "Chanelle",
                            HomeAddress = "95314 Senger Lakes",
                            LastName = "Reilly",
                            RoleId = 5,
                            Salary = 1582
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(1997, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(5692),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(5702),
                            FirstName = "Ross",
                            HomeAddress = "0502 Chauncey Loaf",
                            LastName = "Steuber",
                            RoleId = 1,
                            Salary = 2847
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(1970, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(6851),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(6861),
                            FirstName = "Timmy",
                            HomeAddress = "7520 Kshlerin Brook",
                            LastName = "Terry",
                            RoleId = 2,
                            Salary = 2514
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(1959, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(8084),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(8093),
                            FirstName = "Bette",
                            HomeAddress = "332 Beier Circles",
                            LastName = "Kuhn",
                            RoleId = 5,
                            Salary = 2731
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(1977, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(9959),
                            BossId = 2,
                            EmploymentDate = new DateTime(2004, 1, 28, 23, 54, 56, 157, DateTimeKind.Local).AddTicks(9968),
                            FirstName = "Coralie",
                            HomeAddress = "96960 Rocky Drive",
                            LastName = "Barton",
                            RoleId = 4,
                            Salary = 2187
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(1959, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(1095),
                            BossId = 5,
                            EmploymentDate = new DateTime(2009, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(1104),
                            FirstName = "Alexandrea",
                            HomeAddress = "7597 Gorczany Square",
                            LastName = "Little",
                            RoleId = 3,
                            Salary = 1671
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(1965, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(2260),
                            BossId = 1,
                            EmploymentDate = new DateTime(2016, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(2269),
                            FirstName = "Cali",
                            HomeAddress = "494 Braun Passage",
                            LastName = "Cummings",
                            RoleId = 4,
                            Salary = 2096
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(1969, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(3457),
                            BossId = 3,
                            EmploymentDate = new DateTime(2014, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(3466),
                            FirstName = "Trevor",
                            HomeAddress = "07818 Greenfelder Street",
                            LastName = "Ratke",
                            RoleId = 3,
                            Salary = 2308
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(1992, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(4662),
                            BossId = 3,
                            EmploymentDate = new DateTime(2002, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(4671),
                            FirstName = "Nannie",
                            HomeAddress = "53913 Hodkiewicz Dam",
                            LastName = "Crona",
                            RoleId = 3,
                            Salary = 2124
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(2000, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(6434),
                            BossId = 2,
                            EmploymentDate = new DateTime(2005, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(6443),
                            FirstName = "Sheila",
                            HomeAddress = "80844 Stacey Mountains",
                            LastName = "Huels",
                            RoleId = 2,
                            Salary = 1311
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(1985, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(8215),
                            BossId = 3,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(8224),
                            FirstName = "Clarissa",
                            HomeAddress = "7866 Kaleigh Prairie",
                            LastName = "Wiegand",
                            RoleId = 2,
                            Salary = 1676
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(1998, 1, 28, 23, 54, 56, 158, DateTimeKind.Local).AddTicks(9992),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(1),
                            FirstName = "Cornelius",
                            HomeAddress = "21895 Myron Throughway",
                            LastName = "Runte",
                            RoleId = 2,
                            Salary = 1190
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(1985, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(1781),
                            BossId = 1,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(1790),
                            FirstName = "Destinee",
                            HomeAddress = "5242 Greta Court",
                            LastName = "Jacobs",
                            RoleId = 1,
                            Salary = 1103
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(1966, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(3542),
                            BossId = 5,
                            EmploymentDate = new DateTime(2021, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(3551),
                            FirstName = "Sandra",
                            HomeAddress = "474 Dahlia Neck",
                            LastName = "Maggio",
                            RoleId = 1,
                            Salary = 2933
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(1958, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(5344),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(5354),
                            FirstName = "Hilbert",
                            HomeAddress = "4280 Max Lane",
                            LastName = "Hamill",
                            RoleId = 3,
                            Salary = 2741
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(1960, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(7126),
                            BossId = 1,
                            EmploymentDate = new DateTime(2011, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(7136),
                            FirstName = "Libbie",
                            HomeAddress = "3118 Allison Fort",
                            LastName = "Abernathy",
                            RoleId = 5,
                            Salary = 1248
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(1958, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(8895),
                            BossId = 5,
                            EmploymentDate = new DateTime(2017, 1, 28, 23, 54, 56, 159, DateTimeKind.Local).AddTicks(8904),
                            FirstName = "Idell",
                            HomeAddress = "624 Danika Lakes",
                            LastName = "Brakus",
                            RoleId = 2,
                            Salary = 2999
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(1955, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(686),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(695),
                            FirstName = "Gracie",
                            HomeAddress = "69202 Carlo Lane",
                            LastName = "Maggio",
                            RoleId = 1,
                            Salary = 1517
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(1955, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(1824),
                            BossId = 3,
                            EmploymentDate = new DateTime(2017, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(1833),
                            FirstName = "Malvina",
                            HomeAddress = "143 Kshlerin Fort",
                            LastName = "Carter",
                            RoleId = 3,
                            Salary = 1108
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(1995, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(2987),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(2996),
                            FirstName = "Alan",
                            HomeAddress = "8269 Ryan Estates",
                            LastName = "Goldner",
                            RoleId = 3,
                            Salary = 2843
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(1964, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(4155),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(4163),
                            FirstName = "Jairo",
                            HomeAddress = "13144 Zulauf Stravenue",
                            LastName = "Gaylord",
                            RoleId = 1,
                            Salary = 1186
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(1962, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(5329),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 1, 28, 23, 54, 56, 160, DateTimeKind.Local).AddTicks(5338),
                            FirstName = "Sylvester",
                            HomeAddress = "1285 Ankunding Haven",
                            LastName = "Leannon",
                            RoleId = 3,
                            Salary = 2567
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intermediate Specialist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Junior Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entry-level specialist"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Employee", b =>
                {
                    b.HasOne("EmployeeMangement.Models.Boss", "Boss")
                        .WithMany("Employees")
                        .HasForeignKey("BossId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeMangement.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
