// <auto-generated />
using System;
using EmployeeMangement.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMangement.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20220130164610_EmployeeCreater")]
    partial class EmployeeCreater
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeMangement.Models.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bosses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Pearlie",
                            LastName = "Strosin"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Eda",
                            LastName = "Spinka"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Otilia",
                            LastName = "Zboncak"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Dovie",
                            LastName = "Abshire"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Matt",
                            LastName = "Homenick"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BossId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1954, 1, 30, 18, 46, 9, 953, DateTimeKind.Local).AddTicks(5987),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 953, DateTimeKind.Local).AddTicks(6894),
                            FirstName = "Geo",
                            HomeAddress = "392 Hettie Court",
                            LastName = "Eichmann",
                            RoleId = 3,
                            Salary = 2646
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1964, 1, 30, 18, 46, 9, 953, DateTimeKind.Local).AddTicks(8869),
                            BossId = 2,
                            EmploymentDate = new DateTime(2012, 1, 30, 18, 46, 9, 953, DateTimeKind.Local).AddTicks(8899),
                            FirstName = "Jennifer",
                            HomeAddress = "718 Kuhlman Way",
                            LastName = "Treutel",
                            RoleId = 3,
                            Salary = 2660
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1964, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(915),
                            BossId = 5,
                            EmploymentDate = new DateTime(2019, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(946),
                            FirstName = "Berenice",
                            HomeAddress = "80838 Vern Oval",
                            LastName = "Greenfelder",
                            RoleId = 1,
                            Salary = 1228
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1960, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(2159),
                            BossId = 2,
                            EmploymentDate = new DateTime(2017, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(2169),
                            FirstName = "Roslyn",
                            HomeAddress = "67852 Schoen Pike",
                            LastName = "Kovacek",
                            RoleId = 2,
                            Salary = 2732
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1957, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(3461),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(3471),
                            FirstName = "Grace",
                            HomeAddress = "7580 Quigley Ferry",
                            LastName = "Nikolaus",
                            RoleId = 1,
                            Salary = 2177
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2002, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(5400),
                            BossId = 5,
                            EmploymentDate = new DateTime(2013, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(5410),
                            FirstName = "Katelyn",
                            HomeAddress = "266 Clifton Gateway",
                            LastName = "Braun",
                            RoleId = 2,
                            Salary = 1769
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1970, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(6614),
                            BossId = 1,
                            EmploymentDate = new DateTime(2002, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(6624),
                            FirstName = "Clemmie",
                            HomeAddress = "12805 Altenwerth Run",
                            LastName = "Okuneva",
                            RoleId = 3,
                            Salary = 1625
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1957, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(7864),
                            BossId = 5,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(7874),
                            FirstName = "Kaylah",
                            HomeAddress = "670 Thiel Place",
                            LastName = "Jacobs",
                            RoleId = 5,
                            Salary = 2258
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1973, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(9771),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 954, DateTimeKind.Local).AddTicks(9781),
                            FirstName = "Ova",
                            HomeAddress = "5759 Fausto Roads",
                            LastName = "Rau",
                            RoleId = 5,
                            Salary = 1355
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1990, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(1716),
                            BossId = 4,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(1725),
                            FirstName = "Cornell",
                            HomeAddress = "1867 Syble Loop",
                            LastName = "Nicolas",
                            RoleId = 3,
                            Salary = 1571
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1968, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(3600),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(3616),
                            FirstName = "Adrienne",
                            HomeAddress = "127 Hailey Creek",
                            LastName = "Littel",
                            RoleId = 4,
                            Salary = 2518
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1959, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(4986),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(5005),
                            FirstName = "Eve",
                            HomeAddress = "590 Goyette Gardens",
                            LastName = "Bartoletti",
                            RoleId = 5,
                            Salary = 1183
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1964, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(6174),
                            BossId = 5,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(6184),
                            FirstName = "Bria",
                            HomeAddress = "37240 Cremin Ville",
                            LastName = "Gulgowski",
                            RoleId = 5,
                            Salary = 2872
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1988, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(8095),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(8106),
                            FirstName = "Mozelle",
                            HomeAddress = "426 Peyton Rapid",
                            LastName = "Mann",
                            RoleId = 2,
                            Salary = 1495
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1972, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(9557),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 1, 30, 18, 46, 9, 955, DateTimeKind.Local).AddTicks(9569),
                            FirstName = "Rachel",
                            HomeAddress = "52841 Ernser Center",
                            LastName = "Simonis",
                            RoleId = 3,
                            Salary = 2306
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1971, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(754),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(764),
                            FirstName = "Fidel",
                            HomeAddress = "9085 Hand Cove",
                            LastName = "Auer",
                            RoleId = 3,
                            Salary = 2459
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1992, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(2601),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(2611),
                            FirstName = "Giovani",
                            HomeAddress = "40289 Adalberto Brooks",
                            LastName = "Parker",
                            RoleId = 5,
                            Salary = 1155
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1978, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(3815),
                            BossId = 3,
                            EmploymentDate = new DateTime(2017, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(3825),
                            FirstName = "Dan",
                            HomeAddress = "98234 Romaguera Prairie",
                            LastName = "Nienow",
                            RoleId = 4,
                            Salary = 2336
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1997, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(5863),
                            BossId = 1,
                            EmploymentDate = new DateTime(2022, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(5873),
                            FirstName = "Luz",
                            HomeAddress = "021 Bartholome Roads",
                            LastName = "Schinner",
                            RoleId = 2,
                            Salary = 2856
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1985, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(7079),
                            BossId = 2,
                            EmploymentDate = new DateTime(2014, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(7089),
                            FirstName = "Emmy",
                            HomeAddress = "75256 Wintheiser Underpass",
                            LastName = "Torphy",
                            RoleId = 1,
                            Salary = 2807
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1959, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(8915),
                            BossId = 5,
                            EmploymentDate = new DateTime(2022, 1, 30, 18, 46, 9, 956, DateTimeKind.Local).AddTicks(8924),
                            FirstName = "Gordon",
                            HomeAddress = "069 Korbin Ramp",
                            LastName = "Wisozk",
                            RoleId = 1,
                            Salary = 1732
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1990, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(103),
                            BossId = 3,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(111),
                            FirstName = "Chaz",
                            HomeAddress = "04585 Schoen Gardens",
                            LastName = "Balistreri",
                            RoleId = 4,
                            Salary = 1530
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1989, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(1325),
                            BossId = 1,
                            EmploymentDate = new DateTime(2010, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(1335),
                            FirstName = "Elna",
                            HomeAddress = "044 Gutmann Walk",
                            LastName = "Cassin",
                            RoleId = 3,
                            Salary = 1629
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1954, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(2507),
                            BossId = 5,
                            EmploymentDate = new DateTime(2016, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(2516),
                            FirstName = "Furman",
                            HomeAddress = "50380 Beer Estates",
                            LastName = "Labadie",
                            RoleId = 5,
                            Salary = 1548
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1959, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(4370),
                            BossId = 5,
                            EmploymentDate = new DateTime(2011, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(4379),
                            FirstName = "Agustin",
                            HomeAddress = "399 Lucinda Drives",
                            LastName = "Swaniawski",
                            RoleId = 1,
                            Salary = 1762
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1980, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(6203),
                            BossId = 1,
                            EmploymentDate = new DateTime(2005, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(6213),
                            FirstName = "Rodrigo",
                            HomeAddress = "70159 Jessyca Divide",
                            LastName = "Mitchell",
                            RoleId = 4,
                            Salary = 1821
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2004, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(8095),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(8105),
                            FirstName = "Edwina",
                            HomeAddress = "43846 Garrick Mountain",
                            LastName = "Runolfsson",
                            RoleId = 4,
                            Salary = 2532
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1986, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(9943),
                            BossId = 1,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 957, DateTimeKind.Local).AddTicks(9953),
                            FirstName = "Hermann",
                            HomeAddress = "657 Wyman Ford",
                            LastName = "Stracke",
                            RoleId = 1,
                            Salary = 2698
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(2003, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(1930),
                            BossId = 1,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(1941),
                            FirstName = "Adolph",
                            HomeAddress = "648 Kayli Run",
                            LastName = "Schuppe",
                            RoleId = 1,
                            Salary = 1833
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1968, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(3303),
                            BossId = 3,
                            EmploymentDate = new DateTime(2002, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(3314),
                            FirstName = "George",
                            HomeAddress = "44323 Howe Turnpike",
                            LastName = "Heidenreich",
                            RoleId = 5,
                            Salary = 2326
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1960, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(4537),
                            BossId = 4,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(4546),
                            FirstName = "Freeman",
                            HomeAddress = "2982 Hudson Port",
                            LastName = "Hyatt",
                            RoleId = 4,
                            Salary = 1744
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(1973, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(5726),
                            BossId = 3,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(5735),
                            FirstName = "Billy",
                            HomeAddress = "578 Bergnaum Route",
                            LastName = "Stehr",
                            RoleId = 4,
                            Salary = 2402
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(1994, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(6921),
                            BossId = 1,
                            EmploymentDate = new DateTime(2021, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(6930),
                            FirstName = "Norene",
                            HomeAddress = "858 Mann Dam",
                            LastName = "Abshire",
                            RoleId = 2,
                            Salary = 2796
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(1994, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(8095),
                            BossId = 5,
                            EmploymentDate = new DateTime(2015, 1, 30, 18, 46, 9, 958, DateTimeKind.Local).AddTicks(8104),
                            FirstName = "Hollie",
                            HomeAddress = "5240 Hane Crossroad",
                            LastName = "Skiles",
                            RoleId = 2,
                            Salary = 1315
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1982, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(125),
                            BossId = 5,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(136),
                            FirstName = "Beatrice",
                            HomeAddress = "68960 Adalberto Ports",
                            LastName = "Metz",
                            RoleId = 5,
                            Salary = 2497
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1955, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(2011),
                            BossId = 1,
                            EmploymentDate = new DateTime(2010, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(2021),
                            FirstName = "Alexa",
                            HomeAddress = "16790 Aric Cape",
                            LastName = "Hamill",
                            RoleId = 2,
                            Salary = 1046
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1989, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(3232),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(3241),
                            FirstName = "Savannah",
                            HomeAddress = "66869 White Trace",
                            LastName = "Volkman",
                            RoleId = 1,
                            Salary = 1257
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1966, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(4463),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(4473),
                            FirstName = "Keyon",
                            HomeAddress = "77348 Witting Run",
                            LastName = "Sanford",
                            RoleId = 5,
                            Salary = 1028
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1975, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(5655),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(5664),
                            FirstName = "Odessa",
                            HomeAddress = "6149 Schinner Estate",
                            LastName = "Kassulke",
                            RoleId = 3,
                            Salary = 2469
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1974, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(6862),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(6871),
                            FirstName = "Calista",
                            HomeAddress = "00518 Jones Locks",
                            LastName = "Schamberger",
                            RoleId = 2,
                            Salary = 2015
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1959, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(8058),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(8068),
                            FirstName = "Rachelle",
                            HomeAddress = "9922 Keebler Islands",
                            LastName = "Bechtelar",
                            RoleId = 3,
                            Salary = 2101
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(2000, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(9275),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 959, DateTimeKind.Local).AddTicks(9285),
                            FirstName = "Bridget",
                            HomeAddress = "9772 Dach Club",
                            LastName = "Kassulke",
                            RoleId = 2,
                            Salary = 1321
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(1992, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(1138),
                            BossId = 1,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(1148),
                            FirstName = "Buster",
                            HomeAddress = "61569 Destinee Station",
                            LastName = "Beier",
                            RoleId = 2,
                            Salary = 2362
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1954, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(3005),
                            BossId = 1,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(3014),
                            FirstName = "Oscar",
                            HomeAddress = "140 Rosetta Rapid",
                            LastName = "Auer",
                            RoleId = 3,
                            Salary = 1021
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1954, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(4888),
                            BossId = 5,
                            EmploymentDate = new DateTime(2014, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(4898),
                            FirstName = "Izaiah",
                            HomeAddress = "245 Geoffrey Mission",
                            LastName = "Wolf",
                            RoleId = 2,
                            Salary = 1618
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(1992, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(6173),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(6183),
                            FirstName = "Mabel",
                            HomeAddress = "67590 Gutkowski Port",
                            LastName = "Schmitt",
                            RoleId = 4,
                            Salary = 1531
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1987, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(8047),
                            BossId = 1,
                            EmploymentDate = new DateTime(2013, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(8057),
                            FirstName = "Simeon",
                            HomeAddress = "73448 Kiarra Ford",
                            LastName = "Gislason",
                            RoleId = 2,
                            Salary = 1096
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1978, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(9252),
                            BossId = 5,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 960, DateTimeKind.Local).AddTicks(9262),
                            FirstName = "Luther",
                            HomeAddress = "4518 Brekke Villages",
                            LastName = "Feest",
                            RoleId = 5,
                            Salary = 2028
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(1984, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(510),
                            BossId = 5,
                            EmploymentDate = new DateTime(2021, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(520),
                            FirstName = "Alana",
                            HomeAddress = "621 Hegmann Plaza",
                            LastName = "Marks",
                            RoleId = 2,
                            Salary = 2604
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(1969, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(2511),
                            BossId = 2,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(2521),
                            FirstName = "Caleb",
                            HomeAddress = "1312 Ambrose Coves",
                            LastName = "Walsh",
                            RoleId = 1,
                            Salary = 2310
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(1986, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(3753),
                            BossId = 5,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(3763),
                            FirstName = "Marta",
                            HomeAddress = "011 Reynolds Cliffs",
                            LastName = "Satterfield",
                            RoleId = 4,
                            Salary = 1043
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(1958, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(5706),
                            BossId = 3,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(5716),
                            FirstName = "Osvaldo",
                            HomeAddress = "0197 Korey Fords",
                            LastName = "Kshlerin",
                            RoleId = 5,
                            Salary = 1614
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(1976, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(6921),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(6931),
                            FirstName = "Stan",
                            HomeAddress = "269 Hickle Fork",
                            LastName = "Rosenbaum",
                            RoleId = 2,
                            Salary = 1960
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(1979, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(8275),
                            BossId = 3,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(8284),
                            FirstName = "Jason",
                            HomeAddress = "302 Schoen Skyway",
                            LastName = "Bernhard",
                            RoleId = 4,
                            Salary = 1380
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(1958, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(9529),
                            BossId = 4,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 961, DateTimeKind.Local).AddTicks(9538),
                            FirstName = "Kieran",
                            HomeAddress = "214 McCullough Camp",
                            LastName = "Ondricka",
                            RoleId = 3,
                            Salary = 1204
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(1976, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(1452),
                            BossId = 5,
                            EmploymentDate = new DateTime(2022, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(1462),
                            FirstName = "Celestine",
                            HomeAddress = "1780 Sid Way",
                            LastName = "Pacocha",
                            RoleId = 5,
                            Salary = 2847
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(1990, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(2752),
                            BossId = 5,
                            EmploymentDate = new DateTime(2012, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(2761),
                            FirstName = "Demetris",
                            HomeAddress = "2887 Goodwin Common",
                            LastName = "Gulgowski",
                            RoleId = 5,
                            Salary = 2313
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(2001, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(4096),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(4106),
                            FirstName = "Dovie",
                            HomeAddress = "80956 Wunsch Island",
                            LastName = "Keeling",
                            RoleId = 3,
                            Salary = 1041
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(1963, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(6076),
                            BossId = 3,
                            EmploymentDate = new DateTime(2012, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(6107),
                            FirstName = "Okey",
                            HomeAddress = "82722 Rosendo Pike",
                            LastName = "Abshire",
                            RoleId = 4,
                            Salary = 2918
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(1955, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(7416),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(7425),
                            FirstName = "Amari",
                            HomeAddress = "7563 Schuster Village",
                            LastName = "Glover",
                            RoleId = 3,
                            Salary = 1930
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(1999, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(9373),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 962, DateTimeKind.Local).AddTicks(9382),
                            FirstName = "Anabelle",
                            HomeAddress = "8178 Oswald Motorway",
                            LastName = "McGlynn",
                            RoleId = 4,
                            Salary = 1229
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(1984, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(1323),
                            BossId = 1,
                            EmploymentDate = new DateTime(2022, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(1333),
                            FirstName = "Brooke",
                            HomeAddress = "1088 Giles Ports",
                            LastName = "Kuvalis",
                            RoleId = 5,
                            Salary = 1679
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(1982, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(3225),
                            BossId = 4,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(3235),
                            FirstName = "Stuart",
                            HomeAddress = "158 Anibal Plaza",
                            LastName = "O'Connell",
                            RoleId = 1,
                            Salary = 1019
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(1992, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(4531),
                            BossId = 3,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(4540),
                            FirstName = "Davon",
                            HomeAddress = "4676 Powlowski Neck",
                            LastName = "Leuschke",
                            RoleId = 5,
                            Salary = 2543
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(1985, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(5867),
                            BossId = 4,
                            EmploymentDate = new DateTime(2006, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(5877),
                            FirstName = "Jerrell",
                            HomeAddress = "2185 Bogisich Corner",
                            LastName = "Runte",
                            RoleId = 5,
                            Salary = 2815
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(1990, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(7809),
                            BossId = 4,
                            EmploymentDate = new DateTime(2012, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(7818),
                            FirstName = "Kristofer",
                            HomeAddress = "7498 Axel Run",
                            LastName = "Bode",
                            RoleId = 4,
                            Salary = 2351
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(1989, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(9082),
                            BossId = 3,
                            EmploymentDate = new DateTime(2014, 1, 30, 18, 46, 9, 963, DateTimeKind.Local).AddTicks(9091),
                            FirstName = "Alex",
                            HomeAddress = "53210 Emard Burg",
                            LastName = "McDermott",
                            RoleId = 1,
                            Salary = 2363
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(1959, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(413),
                            BossId = 4,
                            EmploymentDate = new DateTime(2017, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(422),
                            FirstName = "Abbigail",
                            HomeAddress = "748 Howell Mountain",
                            LastName = "Grimes",
                            RoleId = 5,
                            Salary = 2970
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(1999, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(1669),
                            BossId = 1,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(1679),
                            FirstName = "Dino",
                            HomeAddress = "0408 Kertzmann Shores",
                            LastName = "Stark",
                            RoleId = 2,
                            Salary = 1766
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(1975, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(3029),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(3039),
                            FirstName = "Bill",
                            HomeAddress = "10006 Schaefer Manors",
                            LastName = "Brown",
                            RoleId = 2,
                            Salary = 2485
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(1986, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(4253),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(4263),
                            FirstName = "Samantha",
                            HomeAddress = "748 Grady Unions",
                            LastName = "Pollich",
                            RoleId = 3,
                            Salary = 1498
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(1968, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(5482),
                            BossId = 4,
                            EmploymentDate = new DateTime(2016, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(5492),
                            FirstName = "Amelia",
                            HomeAddress = "003 Herman Turnpike",
                            LastName = "Satterfield",
                            RoleId = 5,
                            Salary = 2496
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(1960, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(6744),
                            BossId = 2,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(6754),
                            FirstName = "Rozella",
                            HomeAddress = "73362 Wyman Fort",
                            LastName = "Franecki",
                            RoleId = 4,
                            Salary = 2421
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(1953, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(8722),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(8731),
                            FirstName = "Elsa",
                            HomeAddress = "598 Audie Meadow",
                            LastName = "Kling",
                            RoleId = 2,
                            Salary = 2710
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(1985, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(9948),
                            BossId = 5,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 964, DateTimeKind.Local).AddTicks(9957),
                            FirstName = "Dario",
                            HomeAddress = "59893 Cartwright Manor",
                            LastName = "Orn",
                            RoleId = 1,
                            Salary = 1520
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(1995, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(1126),
                            BossId = 1,
                            EmploymentDate = new DateTime(2002, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(1135),
                            FirstName = "Vito",
                            HomeAddress = "44019 King Locks",
                            LastName = "Quitzon",
                            RoleId = 2,
                            Salary = 2069
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(1998, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(2396),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(2405),
                            FirstName = "Alaina",
                            HomeAddress = "4915 Hagenes Lake",
                            LastName = "Lubowitz",
                            RoleId = 5,
                            Salary = 2911
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(1998, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(3659),
                            BossId = 4,
                            EmploymentDate = new DateTime(2006, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(3669),
                            FirstName = "Carrie",
                            HomeAddress = "37832 Stroman Valley",
                            LastName = "King",
                            RoleId = 4,
                            Salary = 1513
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(1993, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(5630),
                            BossId = 5,
                            EmploymentDate = new DateTime(2004, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(5640),
                            FirstName = "Naomi",
                            HomeAddress = "75359 Nico Lock",
                            LastName = "Kulas",
                            RoleId = 1,
                            Salary = 1957
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(1964, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(6830),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(6839),
                            FirstName = "Lillie",
                            HomeAddress = "60955 Nolan Stravenue",
                            LastName = "Buckridge",
                            RoleId = 3,
                            Salary = 2939
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(1971, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(8752),
                            BossId = 2,
                            EmploymentDate = new DateTime(2008, 1, 30, 18, 46, 9, 965, DateTimeKind.Local).AddTicks(8762),
                            FirstName = "Randall",
                            HomeAddress = "452 Ian Rapids",
                            LastName = "Dibbert",
                            RoleId = 4,
                            Salary = 1212
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(1967, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(52),
                            BossId = 2,
                            EmploymentDate = new DateTime(2019, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(62),
                            FirstName = "Nash",
                            HomeAddress = "967 Lesch Hill",
                            LastName = "Denesik",
                            RoleId = 1,
                            Salary = 1319
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(1984, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(1299),
                            BossId = 3,
                            EmploymentDate = new DateTime(2021, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(1308),
                            FirstName = "Tobin",
                            HomeAddress = "6317 Friesen Ranch",
                            LastName = "Kshlerin",
                            RoleId = 1,
                            Salary = 1531
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(1966, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(2525),
                            BossId = 4,
                            EmploymentDate = new DateTime(2002, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(2535),
                            FirstName = "Layne",
                            HomeAddress = "258 Hammes Radial",
                            LastName = "Schmidt",
                            RoleId = 3,
                            Salary = 1523
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(1974, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(3697),
                            BossId = 2,
                            EmploymentDate = new DateTime(2005, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(3706),
                            FirstName = "Jaycee",
                            HomeAddress = "126 Purdy Bypass",
                            LastName = "Kreiger",
                            RoleId = 3,
                            Salary = 2796
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(1964, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(4874),
                            BossId = 5,
                            EmploymentDate = new DateTime(2002, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(4884),
                            FirstName = "Odell",
                            HomeAddress = "367 Zemlak Union",
                            LastName = "Russel",
                            RoleId = 5,
                            Salary = 2579
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(1956, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(6105),
                            BossId = 3,
                            EmploymentDate = new DateTime(2009, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(6115),
                            FirstName = "Hassie",
                            HomeAddress = "64061 Quigley Gateway",
                            LastName = "O'Hara",
                            RoleId = 2,
                            Salary = 2253
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(1953, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(7412),
                            BossId = 1,
                            EmploymentDate = new DateTime(2018, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(7422),
                            FirstName = "Angie",
                            HomeAddress = "93409 Reynolds Wall",
                            LastName = "Breitenberg",
                            RoleId = 1,
                            Salary = 2252
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(1958, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(8627),
                            BossId = 4,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(8637),
                            FirstName = "Brendon",
                            HomeAddress = "09510 Muller Inlet",
                            LastName = "Stokes",
                            RoleId = 5,
                            Salary = 1893
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(1995, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(9780),
                            BossId = 1,
                            EmploymentDate = new DateTime(2017, 1, 30, 18, 46, 9, 966, DateTimeKind.Local).AddTicks(9789),
                            FirstName = "Niko",
                            HomeAddress = "718 Murray Land",
                            LastName = "Brekke",
                            RoleId = 4,
                            Salary = 1761
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(1969, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(1601),
                            BossId = 3,
                            EmploymentDate = new DateTime(2014, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(1611),
                            FirstName = "Garett",
                            HomeAddress = "1789 Iva Bridge",
                            LastName = "Ruecker",
                            RoleId = 3,
                            Salary = 1663
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(1980, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(2846),
                            BossId = 2,
                            EmploymentDate = new DateTime(2006, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(2856),
                            FirstName = "Marcos",
                            HomeAddress = "60390 Oberbrunner Meadow",
                            LastName = "Altenwerth",
                            RoleId = 2,
                            Salary = 1635
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(1975, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(4785),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(4795),
                            FirstName = "Matilde",
                            HomeAddress = "95406 Dillan Parkways",
                            LastName = "Friesen",
                            RoleId = 1,
                            Salary = 1282
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(1986, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(6618),
                            BossId = 2,
                            EmploymentDate = new DateTime(2001, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(6628),
                            FirstName = "Julio",
                            HomeAddress = "89700 Garnet Pass",
                            LastName = "Predovic",
                            RoleId = 2,
                            Salary = 1078
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(1992, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(8471),
                            BossId = 1,
                            EmploymentDate = new DateTime(2020, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(8481),
                            FirstName = "Marina",
                            HomeAddress = "492 Jaime Extensions",
                            LastName = "Bruen",
                            RoleId = 5,
                            Salary = 2172
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(2003, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(9766),
                            BossId = 4,
                            EmploymentDate = new DateTime(2017, 1, 30, 18, 46, 9, 967, DateTimeKind.Local).AddTicks(9776),
                            FirstName = "Valentin",
                            HomeAddress = "0911 Treutel Heights",
                            LastName = "Gleason",
                            RoleId = 3,
                            Salary = 1191
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(1999, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(1597),
                            BossId = 1,
                            EmploymentDate = new DateTime(2007, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(1607),
                            FirstName = "Brianne",
                            HomeAddress = "636 Jalon Tunnel",
                            LastName = "Reilly",
                            RoleId = 1,
                            Salary = 2144
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(1968, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(3397),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(3406),
                            FirstName = "Adrien",
                            HomeAddress = "29238 Raleigh Trail",
                            LastName = "Eichmann",
                            RoleId = 1,
                            Salary = 1478
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(1996, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(5355),
                            BossId = 1,
                            EmploymentDate = new DateTime(2010, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(5364),
                            FirstName = "Anastacio",
                            HomeAddress = "3668 Raphael Mill",
                            LastName = "Heathcote",
                            RoleId = 3,
                            Salary = 1512
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(1957, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(6582),
                            BossId = 3,
                            EmploymentDate = new DateTime(2005, 1, 30, 18, 46, 9, 968, DateTimeKind.Local).AddTicks(6591),
                            FirstName = "Casey",
                            HomeAddress = "86349 Pagac Lodge",
                            LastName = "Ledner",
                            RoleId = 1,
                            Salary = 1719
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intermediate Specialist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Junior Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entry-level specialist"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Employee", b =>
                {
                    b.HasOne("EmployeeMangement.Models.Boss", "Boss")
                        .WithMany("Employees")
                        .HasForeignKey("BossId");

                    b.HasOne("EmployeeMangement.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
