// <auto-generated />
using System;
using EmployeeMangement.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMangement.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bosses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Walton",
                            LastName = "Crist"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Selena",
                            LastName = "Predovic"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Jonathon",
                            LastName = "Hahn"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Arne",
                            LastName = "Schimmel"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Kayleigh",
                            LastName = "Hudson"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BossId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1977, 2, 23, 23, 37, 34, 584, DateTimeKind.Local).AddTicks(7834),
                            BossId = 4,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 584, DateTimeKind.Local).AddTicks(8792),
                            FirstName = "Angelica",
                            HomeAddress = "09277 Welch Terrace",
                            LastName = "Jast",
                            RoleId = 1,
                            Salary = 2892
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1982, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(298),
                            BossId = 5,
                            EmploymentDate = new DateTime(2011, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(316),
                            FirstName = "Marian",
                            HomeAddress = "150 McCullough Parkway",
                            LastName = "Gottlieb",
                            RoleId = 1,
                            Salary = 1431
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1987, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(1551),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(1580),
                            FirstName = "Adela",
                            HomeAddress = "78005 Sanford Shoal",
                            LastName = "Douglas",
                            RoleId = 3,
                            Salary = 2643
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1982, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(2761),
                            BossId = 1,
                            EmploymentDate = new DateTime(2009, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(2771),
                            FirstName = "Cole",
                            HomeAddress = "8866 Carroll Coves",
                            LastName = "Kshlerin",
                            RoleId = 3,
                            Salary = 2134
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1991, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(4609),
                            BossId = 4,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(4619),
                            FirstName = "Talon",
                            HomeAddress = "9178 Lolita Mountain",
                            LastName = "Gerlach",
                            RoleId = 4,
                            Salary = 2924
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2003, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(6460),
                            BossId = 1,
                            EmploymentDate = new DateTime(2006, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(6470),
                            FirstName = "Alexys",
                            HomeAddress = "88432 Reginald Squares",
                            LastName = "Leannon",
                            RoleId = 1,
                            Salary = 1407
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1955, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(7663),
                            BossId = 3,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(7673),
                            FirstName = "Jacinthe",
                            HomeAddress = "703 Hammes Row",
                            LastName = "Wunsch",
                            RoleId = 3,
                            Salary = 2516
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1966, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(9539),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 585, DateTimeKind.Local).AddTicks(9550),
                            FirstName = "Dereck",
                            HomeAddress = "911 Drake Harbor",
                            LastName = "Witting",
                            RoleId = 2,
                            Salary = 1695
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1986, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(1367),
                            BossId = 3,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(1377),
                            FirstName = "Tony",
                            HomeAddress = "1380 Javon Curve",
                            LastName = "Graham",
                            RoleId = 1,
                            Salary = 2076
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1953, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(3176),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(3185),
                            FirstName = "Brooklyn",
                            HomeAddress = "782 Cathrine Dale",
                            LastName = "Reynolds",
                            RoleId = 4,
                            Salary = 2783
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(4359),
                            BossId = 3,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(4368),
                            FirstName = "Wilfrid",
                            HomeAddress = "52244 Hahn Drive",
                            LastName = "DuBuque",
                            RoleId = 5,
                            Salary = 1568
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1989, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(5533),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(5542),
                            FirstName = "Judy",
                            HomeAddress = "8483 Kerluke Locks",
                            LastName = "Barrows",
                            RoleId = 3,
                            Salary = 1020
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1965, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(6765),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(6774),
                            FirstName = "Dorthy",
                            HomeAddress = "076 Ritchie Plains",
                            LastName = "Barton",
                            RoleId = 5,
                            Salary = 1014
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(7939),
                            BossId = 2,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(7949),
                            FirstName = "Cynthia",
                            HomeAddress = "575 Bruen Hills",
                            LastName = "Eichmann",
                            RoleId = 5,
                            Salary = 2264
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(9763),
                            BossId = 5,
                            EmploymentDate = new DateTime(2003, 2, 23, 23, 37, 34, 586, DateTimeKind.Local).AddTicks(9773),
                            FirstName = "Liana",
                            HomeAddress = "24433 Oren Mountains",
                            LastName = "Carroll",
                            RoleId = 4,
                            Salary = 1478
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1998, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(1594),
                            BossId = 2,
                            EmploymentDate = new DateTime(2012, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(1603),
                            FirstName = "Elena",
                            HomeAddress = "236 Ruthie Mill",
                            LastName = "O'Keefe",
                            RoleId = 2,
                            Salary = 1291
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1986, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(3525),
                            BossId = 4,
                            EmploymentDate = new DateTime(2022, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(3535),
                            FirstName = "Yasmine",
                            HomeAddress = "749 Travon Falls",
                            LastName = "Herman",
                            RoleId = 2,
                            Salary = 2867
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1993, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(4725),
                            BossId = 4,
                            EmploymentDate = new DateTime(2003, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(4735),
                            FirstName = "Leonor",
                            HomeAddress = "8210 Hettinger Mountains",
                            LastName = "Veum",
                            RoleId = 1,
                            Salary = 2490
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1960, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(5891),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(5901),
                            FirstName = "Estevan",
                            HomeAddress = "78986 Schneider Ports",
                            LastName = "Howell",
                            RoleId = 1,
                            Salary = 2730
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1970, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(7742),
                            BossId = 1,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(7752),
                            FirstName = "Jaden",
                            HomeAddress = "05175 Chaya Lock",
                            LastName = "Johns",
                            RoleId = 1,
                            Salary = 1845
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1970, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(8985),
                            BossId = 4,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 587, DateTimeKind.Local).AddTicks(8995),
                            FirstName = "Luz",
                            HomeAddress = "40320 Rippin Mount",
                            LastName = "Dibbert",
                            RoleId = 1,
                            Salary = 1102
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1967, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(872),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(882),
                            FirstName = "Oscar",
                            HomeAddress = "4463 Candido Square",
                            LastName = "Wilkinson",
                            RoleId = 5,
                            Salary = 2324
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1978, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(2698),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(2709),
                            FirstName = "Abbey",
                            HomeAddress = "041 Willow Bridge",
                            LastName = "Bins",
                            RoleId = 3,
                            Salary = 1759
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1969, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(4575),
                            BossId = 3,
                            EmploymentDate = new DateTime(2020, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(4585),
                            FirstName = "Angie",
                            HomeAddress = "01979 Lenny Parkway",
                            LastName = "Walker",
                            RoleId = 1,
                            Salary = 2602
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(5883),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(5892),
                            FirstName = "Agnes",
                            HomeAddress = "4592 Homenick Loop",
                            LastName = "Purdy",
                            RoleId = 1,
                            Salary = 1652
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2003, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(7786),
                            BossId = 1,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(7796),
                            FirstName = "Ramiro",
                            HomeAddress = "379 Tillman Expressway",
                            LastName = "Grady",
                            RoleId = 4,
                            Salary = 1375
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2004, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(8978),
                            BossId = 2,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 588, DateTimeKind.Local).AddTicks(8988),
                            FirstName = "Branson",
                            HomeAddress = "95017 Bayer Walks",
                            LastName = "Willms",
                            RoleId = 3,
                            Salary = 2790
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1975, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(927),
                            BossId = 5,
                            EmploymentDate = new DateTime(2012, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(936),
                            FirstName = "Quentin",
                            HomeAddress = "9449 Randy Course",
                            LastName = "Kuvalis",
                            RoleId = 5,
                            Salary = 2525
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1965, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(2952),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(2962),
                            FirstName = "Abbigail",
                            HomeAddress = "306 Chet Falls",
                            LastName = "Grimes",
                            RoleId = 2,
                            Salary = 1155
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1966, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(4791),
                            BossId = 4,
                            EmploymentDate = new DateTime(2022, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(4800),
                            FirstName = "Erik",
                            HomeAddress = "450 Judson Field",
                            LastName = "Leannon",
                            RoleId = 1,
                            Salary = 1088
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1986, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(6646),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(6657),
                            FirstName = "Gussie",
                            HomeAddress = "1084 Kobe Cape",
                            LastName = "Volkman",
                            RoleId = 3,
                            Salary = 2802
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(2002, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(7896),
                            BossId = 3,
                            EmploymentDate = new DateTime(2014, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(7906),
                            FirstName = "Mallory",
                            HomeAddress = "0652 Hahn Bridge",
                            LastName = "Kerluke",
                            RoleId = 2,
                            Salary = 1286
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(1956, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(9173),
                            BossId = 5,
                            EmploymentDate = new DateTime(2011, 2, 23, 23, 37, 34, 589, DateTimeKind.Local).AddTicks(9183),
                            FirstName = "Bernard",
                            HomeAddress = "6922 Bernhard Street",
                            LastName = "Russel",
                            RoleId = 4,
                            Salary = 1869
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(1984, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(358),
                            BossId = 2,
                            EmploymentDate = new DateTime(2002, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(368),
                            FirstName = "Elmira",
                            HomeAddress = "3154 Conroy Freeway",
                            LastName = "Durgan",
                            RoleId = 1,
                            Salary = 1377
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1980, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(2200),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(2210),
                            FirstName = "Johnpaul",
                            HomeAddress = "93905 Jarvis Club",
                            LastName = "Jewess",
                            RoleId = 1,
                            Salary = 2953
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1998, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(4156),
                            BossId = 1,
                            EmploymentDate = new DateTime(2014, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(4166),
                            FirstName = "Wilbert",
                            HomeAddress = "317 Deion Ports",
                            LastName = "Bogan",
                            RoleId = 2,
                            Salary = 1202
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1983, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(6158),
                            BossId = 3,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(6168),
                            FirstName = "Clifford",
                            HomeAddress = "6453 Coty Row",
                            LastName = "Gleason",
                            RoleId = 3,
                            Salary = 2700
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1979, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(7360),
                            BossId = 5,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(7370),
                            FirstName = "Abel",
                            HomeAddress = "5841 Langosh Harbors",
                            LastName = "Boehm",
                            RoleId = 1,
                            Salary = 1585
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1988, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(9269),
                            BossId = 3,
                            EmploymentDate = new DateTime(2020, 2, 23, 23, 37, 34, 590, DateTimeKind.Local).AddTicks(9279),
                            FirstName = "Abbigail",
                            HomeAddress = "193 Jazmin Vista",
                            LastName = "Harber",
                            RoleId = 1,
                            Salary = 2614
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1964, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(1116),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(1126),
                            FirstName = "Regan",
                            HomeAddress = "9541 Allison Street",
                            LastName = "Hammes",
                            RoleId = 3,
                            Salary = 2988
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1971, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(2449),
                            BossId = 4,
                            EmploymentDate = new DateTime(2014, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(2458),
                            FirstName = "Ollie",
                            HomeAddress = "150 Hirthe Unions",
                            LastName = "Huels",
                            RoleId = 2,
                            Salary = 1687
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(1958, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(4386),
                            BossId = 4,
                            EmploymentDate = new DateTime(2007, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(4396),
                            FirstName = "Kathryne",
                            HomeAddress = "92741 Arthur Stream",
                            LastName = "Cummings",
                            RoleId = 2,
                            Salary = 2915
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(1961, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(5672),
                            BossId = 4,
                            EmploymentDate = new DateTime(2003, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(5681),
                            FirstName = "Eric",
                            HomeAddress = "5435 Armstrong Shores",
                            LastName = "Wiegand",
                            RoleId = 4,
                            Salary = 1351
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1979, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(7529),
                            BossId = 1,
                            EmploymentDate = new DateTime(2016, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(7539),
                            FirstName = "Ransom",
                            HomeAddress = "5126 Amely Pass",
                            LastName = "Carroll",
                            RoleId = 1,
                            Salary = 1594
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1979, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(8778),
                            BossId = 5,
                            EmploymentDate = new DateTime(2007, 2, 23, 23, 37, 34, 591, DateTimeKind.Local).AddTicks(8787),
                            FirstName = "Ashlee",
                            HomeAddress = "422 Windler Skyway",
                            LastName = "Kunze",
                            RoleId = 3,
                            Salary = 2714
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(1998, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(125),
                            BossId = 4,
                            EmploymentDate = new DateTime(2007, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(134),
                            FirstName = "Tomas",
                            HomeAddress = "024 Aufderhar Row",
                            LastName = "Wisozk",
                            RoleId = 4,
                            Salary = 1985
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1993, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(2143),
                            BossId = 2,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(2153),
                            FirstName = "Noah",
                            HomeAddress = "727 Durward Groves",
                            LastName = "Rodriguez",
                            RoleId = 4,
                            Salary = 1765
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1983, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(3961),
                            BossId = 2,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(3971),
                            FirstName = "Camden",
                            HomeAddress = "56750 Delilah Fort",
                            LastName = "Grimes",
                            RoleId = 5,
                            Salary = 2382
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(1997, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(5188),
                            BossId = 5,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(5197),
                            FirstName = "Raquel",
                            HomeAddress = "78351 VonRueden Run",
                            LastName = "Braun",
                            RoleId = 5,
                            Salary = 2191
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(1992, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(6513),
                            BossId = 5,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(6522),
                            FirstName = "Madelynn",
                            HomeAddress = "086 Romaguera Courts",
                            LastName = "Nitzsche",
                            RoleId = 2,
                            Salary = 1462
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(2002, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(8540),
                            BossId = 1,
                            EmploymentDate = new DateTime(2006, 2, 23, 23, 37, 34, 592, DateTimeKind.Local).AddTicks(8550),
                            FirstName = "Antonietta",
                            HomeAddress = "356 Leonora Brook",
                            LastName = "Bailey",
                            RoleId = 3,
                            Salary = 1207
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(1970, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(376),
                            BossId = 3,
                            EmploymentDate = new DateTime(2007, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(385),
                            FirstName = "Milan",
                            HomeAddress = "42655 Morris Junction",
                            LastName = "Little",
                            RoleId = 1,
                            Salary = 2916
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(1967, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(1618),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(1627),
                            FirstName = "Jody",
                            HomeAddress = "43849 Wilkinson Curve",
                            LastName = "Kreiger",
                            RoleId = 5,
                            Salary = 2292
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(1962, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(3598),
                            BossId = 1,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(3607),
                            FirstName = "Chyna",
                            HomeAddress = "575 Chadrick Cliff",
                            LastName = "Schroeder",
                            RoleId = 5,
                            Salary = 1212
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(1974, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(4849),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(4859),
                            FirstName = "Geovanny",
                            HomeAddress = "25230 McKenzie Camp",
                            LastName = "Wiza",
                            RoleId = 4,
                            Salary = 2806
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(1995, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(6774),
                            BossId = 4,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(6784),
                            FirstName = "Herminio",
                            HomeAddress = "7350 Yoshiko Village",
                            LastName = "Kozey",
                            RoleId = 4,
                            Salary = 2188
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(1984, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(8641),
                            BossId = 2,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(8651),
                            FirstName = "Lauriane",
                            HomeAddress = "095 Jeanne Streets",
                            LastName = "Upton",
                            RoleId = 3,
                            Salary = 2671
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(1986, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(9857),
                            BossId = 2,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 593, DateTimeKind.Local).AddTicks(9866),
                            FirstName = "Marlene",
                            HomeAddress = "63380 Watsica Parkways",
                            LastName = "Bednar",
                            RoleId = 2,
                            Salary = 2975
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(1999, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(1135),
                            BossId = 3,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(1144),
                            FirstName = "Estell",
                            HomeAddress = "4579 Wehner Forge",
                            LastName = "Dare",
                            RoleId = 3,
                            Salary = 2819
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(1975, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(2325),
                            BossId = 5,
                            EmploymentDate = new DateTime(2022, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(2334),
                            FirstName = "Mathew",
                            HomeAddress = "79758 Turcotte Burg",
                            LastName = "Gislason",
                            RoleId = 5,
                            Salary = 1456
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(2003, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(4152),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(4161),
                            FirstName = "Leda",
                            HomeAddress = "2685 Hilario Dam",
                            LastName = "Yundt",
                            RoleId = 2,
                            Salary = 2393
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(1982, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(5393),
                            BossId = 3,
                            EmploymentDate = new DateTime(2006, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(5402),
                            FirstName = "Florian",
                            HomeAddress = "8030 Sanford Dam",
                            LastName = "Heaney",
                            RoleId = 3,
                            Salary = 1621
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(1967, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(7287),
                            BossId = 3,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(7297),
                            FirstName = "Hester",
                            HomeAddress = "901 Jesus Ridges",
                            LastName = "Pouros",
                            RoleId = 5,
                            Salary = 1582
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(1995, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(8476),
                            BossId = 2,
                            EmploymentDate = new DateTime(2006, 2, 23, 23, 37, 34, 594, DateTimeKind.Local).AddTicks(8486),
                            FirstName = "Bianka",
                            HomeAddress = "7111 Kub Course",
                            LastName = "Wiza",
                            RoleId = 1,
                            Salary = 2037
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(1963, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(326),
                            BossId = 4,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(336),
                            FirstName = "Tyree",
                            HomeAddress = "22457 Emory Trail",
                            LastName = "Morissette",
                            RoleId = 2,
                            Salary = 1855
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(1993, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(2189),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(2199),
                            FirstName = "Lucius",
                            HomeAddress = "5265 Uriah Pike",
                            LastName = "Windler",
                            RoleId = 3,
                            Salary = 1612
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(1959, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(3354),
                            BossId = 5,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(3364),
                            FirstName = "Aurelia",
                            HomeAddress = "902 Walker Centers",
                            LastName = "Robel",
                            RoleId = 5,
                            Salary = 2863
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(1990, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(4552),
                            BossId = 2,
                            EmploymentDate = new DateTime(2003, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(4562),
                            FirstName = "Alana",
                            HomeAddress = "1524 Adams Burgs",
                            LastName = "Bergstrom",
                            RoleId = 5,
                            Salary = 2490
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(1966, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(6384),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(6394),
                            FirstName = "Karen",
                            HomeAddress = "49110 Trenton Forks",
                            LastName = "Hand",
                            RoleId = 1,
                            Salary = 2682
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(1955, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(7574),
                            BossId = 1,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(7584),
                            FirstName = "Newton",
                            HomeAddress = "4428 Streich Mall",
                            LastName = "Hagenes",
                            RoleId = 4,
                            Salary = 2480
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(1999, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(9409),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 2, 23, 23, 37, 34, 595, DateTimeKind.Local).AddTicks(9418),
                            FirstName = "Janick",
                            HomeAddress = "2283 Sincere Flat",
                            LastName = "Von",
                            RoleId = 4,
                            Salary = 2703
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(1967, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(1257),
                            BossId = 3,
                            EmploymentDate = new DateTime(2016, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(1266),
                            FirstName = "Jess",
                            HomeAddress = "2432 Vella Center",
                            LastName = "Leuschke",
                            RoleId = 2,
                            Salary = 2943
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(3079),
                            BossId = 3,
                            EmploymentDate = new DateTime(2012, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(3088),
                            FirstName = "Katheryn",
                            HomeAddress = "99337 Rahul Motorway",
                            LastName = "Cassin",
                            RoleId = 4,
                            Salary = 2677
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(1988, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(4254),
                            BossId = 3,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(4264),
                            FirstName = "Weston",
                            HomeAddress = "837 Trantow Villages",
                            LastName = "Schmitt",
                            RoleId = 5,
                            Salary = 2754
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(1989, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(5454),
                            BossId = 2,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(5464),
                            FirstName = "Wendell",
                            HomeAddress = "46505 Hammes Land",
                            LastName = "Doyle",
                            RoleId = 4,
                            Salary = 1961
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(1975, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(7296),
                            BossId = 4,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(7306),
                            FirstName = "Milton",
                            HomeAddress = "5864 Marcia Alley",
                            LastName = "Schamberger",
                            RoleId = 5,
                            Salary = 1584
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(1964, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(8502),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 596, DateTimeKind.Local).AddTicks(8512),
                            FirstName = "Jamil",
                            HomeAddress = "899 Walter Knolls",
                            LastName = "McLaughlin",
                            RoleId = 2,
                            Salary = 2232
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(1955, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(351),
                            BossId = 4,
                            EmploymentDate = new DateTime(2001, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(361),
                            FirstName = "Lelah",
                            HomeAddress = "77512 Janice Lock",
                            LastName = "Hegmann",
                            RoleId = 3,
                            Salary = 2489
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(1987, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(2177),
                            BossId = 3,
                            EmploymentDate = new DateTime(2002, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(2186),
                            FirstName = "Jaqueline",
                            HomeAddress = "12915 Kaelyn Trail",
                            LastName = "Krajcik",
                            RoleId = 3,
                            Salary = 2982
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(1954, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(3382),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(3392),
                            FirstName = "Damaris",
                            HomeAddress = "9479 Bernhard Islands",
                            LastName = "Von",
                            RoleId = 5,
                            Salary = 2882
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(1981, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(4572),
                            BossId = 5,
                            EmploymentDate = new DateTime(2021, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(4581),
                            FirstName = "Florencio",
                            HomeAddress = "438 Willms Forest",
                            LastName = "Bashirian",
                            RoleId = 1,
                            Salary = 1752
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(1954, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(6406),
                            BossId = 3,
                            EmploymentDate = new DateTime(2006, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(6416),
                            FirstName = "Peggie",
                            HomeAddress = "6655 Kara Ferry",
                            LastName = "Borer",
                            RoleId = 3,
                            Salary = 2631
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(1953, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(7596),
                            BossId = 5,
                            EmploymentDate = new DateTime(2018, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(7606),
                            FirstName = "Fernando",
                            HomeAddress = "22959 O'Keefe Orchard",
                            LastName = "Bechtelar",
                            RoleId = 2,
                            Salary = 1237
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(1964, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(9511),
                            BossId = 3,
                            EmploymentDate = new DateTime(2010, 2, 23, 23, 37, 34, 597, DateTimeKind.Local).AddTicks(9546),
                            FirstName = "Darian",
                            HomeAddress = "32998 Justyn Vista",
                            LastName = "Graham",
                            RoleId = 2,
                            Salary = 1518
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(1997, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(1352),
                            BossId = 1,
                            EmploymentDate = new DateTime(2012, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(1362),
                            FirstName = "Alden",
                            HomeAddress = "270 Jerald Mission",
                            LastName = "Kohler",
                            RoleId = 5,
                            Salary = 2802
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(1993, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(2517),
                            BossId = 4,
                            EmploymentDate = new DateTime(2002, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(2526),
                            FirstName = "Don",
                            HomeAddress = "9934 Paucek Ports",
                            LastName = "Kiehn",
                            RoleId = 5,
                            Salary = 2186
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(1983, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(3706),
                            BossId = 4,
                            EmploymentDate = new DateTime(2014, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(3716),
                            FirstName = "Brigitte",
                            HomeAddress = "694 Batz Manors",
                            LastName = "Kshlerin",
                            RoleId = 5,
                            Salary = 2129
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(1956, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(5664),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(5674),
                            FirstName = "Cedrick",
                            HomeAddress = "98828 Martina Overpass",
                            LastName = "Morissette",
                            RoleId = 4,
                            Salary = 1950
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(1985, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(7501),
                            BossId = 1,
                            EmploymentDate = new DateTime(2019, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(7511),
                            FirstName = "Doug",
                            HomeAddress = "318 Stanford Junctions",
                            LastName = "Hyatt",
                            RoleId = 2,
                            Salary = 1051
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(1994, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(8674),
                            BossId = 3,
                            EmploymentDate = new DateTime(2017, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(8684),
                            FirstName = "Charlotte",
                            HomeAddress = "65475 Quigley Mews",
                            LastName = "Cormier",
                            RoleId = 4,
                            Salary = 2782
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(1998, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(9873),
                            BossId = 1,
                            EmploymentDate = new DateTime(2014, 2, 23, 23, 37, 34, 598, DateTimeKind.Local).AddTicks(9883),
                            FirstName = "Elmo",
                            HomeAddress = "91733 Mraz Spur",
                            LastName = "Boehm",
                            RoleId = 4,
                            Salary = 2792
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(1981, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(1847),
                            BossId = 2,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(1857),
                            FirstName = "Roberto",
                            HomeAddress = "13847 Sherman Rapid",
                            LastName = "McDermott",
                            RoleId = 2,
                            Salary = 2658
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(1991, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(3724),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(3733),
                            FirstName = "Sven",
                            HomeAddress = "87523 Dorothea Junctions",
                            LastName = "Bashirian",
                            RoleId = 3,
                            Salary = 1438
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(1994, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(4923),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(4932),
                            FirstName = "Kaleb",
                            HomeAddress = "06352 Nitzsche Streets",
                            LastName = "Robel",
                            RoleId = 4,
                            Salary = 1676
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(1960, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(6833),
                            BossId = 5,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(6843),
                            FirstName = "Evie",
                            HomeAddress = "18362 Madisyn Lake",
                            LastName = "Macejkovic",
                            RoleId = 3,
                            Salary = 2801
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(1976, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(8190),
                            BossId = 5,
                            EmploymentDate = new DateTime(2005, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(8200),
                            FirstName = "Bridget",
                            HomeAddress = "3200 Klocko Stravenue",
                            LastName = "Metz",
                            RoleId = 2,
                            Salary = 1586
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(1993, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(9453),
                            BossId = 4,
                            EmploymentDate = new DateTime(2008, 2, 23, 23, 37, 34, 599, DateTimeKind.Local).AddTicks(9462),
                            FirstName = "Chris",
                            HomeAddress = "8149 Denesik Springs",
                            LastName = "Bernier",
                            RoleId = 2,
                            Salary = 2256
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(1966, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(1311),
                            BossId = 4,
                            EmploymentDate = new DateTime(2022, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(1321),
                            FirstName = "Devin",
                            HomeAddress = "1584 Meghan Pine",
                            LastName = "Goodwin",
                            RoleId = 5,
                            Salary = 2018
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(1966, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(2538),
                            BossId = 1,
                            EmploymentDate = new DateTime(2002, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(2548),
                            FirstName = "Kasey",
                            HomeAddress = "261 Lebsack Square",
                            LastName = "Bartell",
                            RoleId = 1,
                            Salary = 2456
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(1990, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(4489),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 2, 23, 23, 37, 34, 600, DateTimeKind.Local).AddTicks(4499),
                            FirstName = "Isaias",
                            HomeAddress = "5074 Jarrod Heights",
                            LastName = "Waelchi",
                            RoleId = 1,
                            Salary = 2424
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAllocation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Felton Road, Sydneymouth, Saint Lucia",
                            MaxAllocation = 17,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Emile Road, Lillaburgh, Cocos (Keeling) Islands",
                            MaxAllocation = 13,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Frederick Trail, Cassieton, India",
                            MaxAllocation = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hodkiewicz Mountains, West Rachael, Equatorial Guinea",
                            MaxAllocation = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Crooks Forges, Lake Paulside, Iran",
                            MaxAllocation = 39,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Miles Curve, North Daijaburgh, Suriname",
                            MaxAllocation = 16,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Friesen Trace, Johnpaulfurt, Faroe Islands",
                            MaxAllocation = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Kennedy Pass, New Ari, Saint Helena",
                            MaxAllocation = 21,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Farrell Ridges, Fisherview, Bahrain",
                            MaxAllocation = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Keenan Shores, Port Taylorchester, Marshall Islands",
                            MaxAllocation = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Zemlak Canyon, Willamouth, Austria",
                            MaxAllocation = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Lon Place, Anyamouth, Iraq",
                            MaxAllocation = 40,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Padberg Terrace, Port Beulahside, Guinea-Bissau",
                            MaxAllocation = 16,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Bergstrom Rest, Eleanorafort, Venezuela",
                            MaxAllocation = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Terry Manor, Dooleybury, Saint Vincent and the Grenadines",
                            MaxAllocation = 50,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Labadie Tunnel, Ardithburgh, Sweden",
                            MaxAllocation = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Davion Fords, Reynoldsstad, Poland",
                            MaxAllocation = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Constantin Branch, McGlynnton, Moldova",
                            MaxAllocation = 11,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Demond Glen, Elmoreborough, Kiribati",
                            MaxAllocation = 29,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Ebert Burg, East Rafaelafort, Madagascar",
                            MaxAllocation = 21,
                            Name = "alias"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intermediate Specialist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Junior Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entry-level specialist"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeMangement.Models.Entities.Boss", "Boss")
                        .WithMany("Employees")
                        .HasForeignKey("BossId");

                    b.HasOne("EmployeeMangement.Models.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
