// <auto-generated />
using System;
using EmployeeMangement.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployeeMangement.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Boss", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bosses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Margarete",
                            LastName = "Ruecker"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Rhett",
                            LastName = "Schulist"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Laura",
                            LastName = "Jakubowski"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Russel",
                            LastName = "Kshlerin"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Gaetano",
                            LastName = "Wilkinson"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("BossId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmploymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BossId");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1958, 2, 24, 22, 31, 3, 781, DateTimeKind.Local).AddTicks(9591),
                            BossId = 2,
                            EmploymentDate = new DateTime(2015, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(510),
                            FirstName = "Erica",
                            HomeAddress = "23104 Bins Viaduct",
                            LastName = "Bahringer",
                            LocationId = 10,
                            RoleId = 3,
                            Salary = 1699
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1993, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(2088),
                            BossId = 1,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(2106),
                            FirstName = "Dan",
                            HomeAddress = "6008 McCullough Junctions",
                            LastName = "Kassulke",
                            LocationId = 17,
                            RoleId = 2,
                            Salary = 2843
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1988, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(3510),
                            BossId = 4,
                            EmploymentDate = new DateTime(2004, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(3521),
                            FirstName = "Kamren",
                            HomeAddress = "072 Auer Ferry",
                            LastName = "Mertz",
                            LocationId = 18,
                            RoleId = 2,
                            Salary = 2123
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(1962, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(5414),
                            BossId = 4,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(5424),
                            FirstName = "Manley",
                            HomeAddress = "7342 Eldridge Squares",
                            LastName = "Hammes",
                            LocationId = 9,
                            RoleId = 1,
                            Salary = 2627
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1969, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(7322),
                            BossId = 1,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(7331),
                            FirstName = "Antwan",
                            HomeAddress = "257 Catherine Estate",
                            LastName = "Leannon",
                            LocationId = 12,
                            RoleId = 4,
                            Salary = 1219
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1983, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(9223),
                            BossId = 5,
                            EmploymentDate = new DateTime(2001, 2, 24, 22, 31, 3, 782, DateTimeKind.Local).AddTicks(9233),
                            FirstName = "Ethan",
                            HomeAddress = "0790 Glenda Highway",
                            LastName = "O'Kon",
                            LocationId = 6,
                            RoleId = 2,
                            Salary = 1830
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1994, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(423),
                            BossId = 2,
                            EmploymentDate = new DateTime(2007, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(432),
                            FirstName = "Monica",
                            HomeAddress = "295 Crona Brook",
                            LastName = "Harris",
                            LocationId = 16,
                            RoleId = 2,
                            Salary = 2858
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(1956, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(1612),
                            BossId = 4,
                            EmploymentDate = new DateTime(2022, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(1621),
                            FirstName = "Glen",
                            HomeAddress = "4964 Parker Cape",
                            LastName = "Tillman",
                            LocationId = 12,
                            RoleId = 2,
                            Salary = 1585
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(2004, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(2821),
                            BossId = 2,
                            EmploymentDate = new DateTime(2012, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(2830),
                            FirstName = "Susie",
                            HomeAddress = "3347 Runte Corners",
                            LastName = "Doyle",
                            LocationId = 6,
                            RoleId = 2,
                            Salary = 2180
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(1983, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(4657),
                            BossId = 2,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(4667),
                            FirstName = "Carlee",
                            HomeAddress = "43359 Alexys Valley",
                            LastName = "Fisher",
                            LocationId = 17,
                            RoleId = 3,
                            Salary = 1903
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1979, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(5822),
                            BossId = 2,
                            EmploymentDate = new DateTime(2002, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(5831),
                            FirstName = "Trycia",
                            HomeAddress = "630 Swift Shoals",
                            LastName = "Wunsch",
                            LocationId = 3,
                            RoleId = 3,
                            Salary = 2338
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(1998, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(7668),
                            BossId = 3,
                            EmploymentDate = new DateTime(2020, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(7678),
                            FirstName = "Felicita",
                            HomeAddress = "193 Kaia Meadow",
                            LastName = "Murazik",
                            LocationId = 2,
                            RoleId = 1,
                            Salary = 1493
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1958, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(8871),
                            BossId = 1,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 783, DateTimeKind.Local).AddTicks(8881),
                            FirstName = "Neal",
                            HomeAddress = "15478 Kohler Cape",
                            LastName = "Green",
                            LocationId = 17,
                            RoleId = 4,
                            Salary = 2315
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(1979, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(74),
                            BossId = 4,
                            EmploymentDate = new DateTime(2018, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(83),
                            FirstName = "Bertram",
                            HomeAddress = "797 Hintz Pass",
                            LastName = "Muller",
                            LocationId = 1,
                            RoleId = 2,
                            Salary = 1265
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(1986, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(1924),
                            BossId = 3,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(1934),
                            FirstName = "Effie",
                            HomeAddress = "01083 Winnifred Inlet",
                            LastName = "Rath",
                            LocationId = 10,
                            RoleId = 4,
                            Salary = 1970
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1992, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(3114),
                            BossId = 4,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(3123),
                            FirstName = "Clementina",
                            HomeAddress = "191 Morissette Meadows",
                            LastName = "Gleichner",
                            LocationId = 6,
                            RoleId = 2,
                            Salary = 1598
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(1991, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(4313),
                            BossId = 1,
                            EmploymentDate = new DateTime(2019, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(4323),
                            FirstName = "Maxwell",
                            HomeAddress = "484 Kessler Pass",
                            LastName = "Nitzsche",
                            LocationId = 15,
                            RoleId = 5,
                            Salary = 1587
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(1988, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(6161),
                            BossId = 1,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(6170),
                            FirstName = "Billie",
                            HomeAddress = "23501 Jamey Green",
                            LastName = "Block",
                            LocationId = 15,
                            RoleId = 5,
                            Salary = 1206
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1965, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(7999),
                            BossId = 3,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(8008),
                            FirstName = "Gerson",
                            HomeAddress = "7385 Jovany Overpass",
                            LastName = "Grimes",
                            LocationId = 1,
                            RoleId = 2,
                            Salary = 2178
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(1987, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(9849),
                            BossId = 2,
                            EmploymentDate = new DateTime(2021, 2, 24, 22, 31, 3, 784, DateTimeKind.Local).AddTicks(9858),
                            FirstName = "Audrey",
                            HomeAddress = "19050 Cassie Ferry",
                            LastName = "Marvin",
                            LocationId = 11,
                            RoleId = 4,
                            Salary = 1681
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1967, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(1059),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(1068),
                            FirstName = "Mckayla",
                            HomeAddress = "505 Beatty Roads",
                            LastName = "Murazik",
                            LocationId = 17,
                            RoleId = 1,
                            Salary = 1538
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(1993, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(2241),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(2250),
                            FirstName = "Cristina",
                            HomeAddress = "6211 Torp Parkway",
                            LastName = "Hauck",
                            LocationId = 13,
                            RoleId = 4,
                            Salary = 2242
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1963, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(4098),
                            BossId = 4,
                            EmploymentDate = new DateTime(2016, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(4108),
                            FirstName = "Trisha",
                            HomeAddress = "452 Eldridge Island",
                            LastName = "Koepp",
                            LocationId = 16,
                            RoleId = 4,
                            Salary = 1279
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(1961, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(5948),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(5958),
                            FirstName = "Emelia",
                            HomeAddress = "645 Paris Green",
                            LastName = "Bergstrom",
                            LocationId = 1,
                            RoleId = 4,
                            Salary = 1339
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(2002, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(7161),
                            BossId = 1,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(7170),
                            FirstName = "Asha",
                            HomeAddress = "7881 Krajcik Radial",
                            LastName = "Connelly",
                            LocationId = 12,
                            RoleId = 2,
                            Salary = 2029
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(1986, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(8344),
                            BossId = 2,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(8353),
                            FirstName = "Steve",
                            HomeAddress = "2979 Yundt Track",
                            LastName = "Langworth",
                            LocationId = 8,
                            RoleId = 5,
                            Salary = 2107
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(1987, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(9546),
                            BossId = 3,
                            EmploymentDate = new DateTime(2015, 2, 24, 22, 31, 3, 785, DateTimeKind.Local).AddTicks(9555),
                            FirstName = "Dakota",
                            HomeAddress = "845 Rau Alley",
                            LastName = "Abernathy",
                            LocationId = 8,
                            RoleId = 4,
                            Salary = 2541
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1988, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(1406),
                            BossId = 1,
                            EmploymentDate = new DateTime(2001, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(1415),
                            FirstName = "Otho",
                            HomeAddress = "8868 Corbin Corners",
                            LastName = "Hackett",
                            LocationId = 18,
                            RoleId = 2,
                            Salary = 2283
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(1992, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(3256),
                            BossId = 1,
                            EmploymentDate = new DateTime(2020, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(3266),
                            FirstName = "Jo",
                            HomeAddress = "08959 Alden Island",
                            LastName = "Tillman",
                            LocationId = 9,
                            RoleId = 3,
                            Salary = 1967
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(1960, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(5131),
                            BossId = 5,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(5141),
                            FirstName = "Carey",
                            HomeAddress = "43970 Jaylon Pike",
                            LastName = "Schneider",
                            LocationId = 2,
                            RoleId = 2,
                            Salary = 2606
                        },
                        new
                        {
                            Id = 31,
                            BirthDate = new DateTime(1985, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(7011),
                            BossId = 3,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(7021),
                            FirstName = "Liliana",
                            HomeAddress = "44464 Kennith Via",
                            LastName = "Wehner",
                            LocationId = 17,
                            RoleId = 5,
                            Salary = 1221
                        },
                        new
                        {
                            Id = 32,
                            BirthDate = new DateTime(1984, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(8211),
                            BossId = 2,
                            EmploymentDate = new DateTime(2022, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(8221),
                            FirstName = "Ethelyn",
                            HomeAddress = "908 Breitenberg Squares",
                            LastName = "Hartmann",
                            LocationId = 14,
                            RoleId = 2,
                            Salary = 2839
                        },
                        new
                        {
                            Id = 33,
                            BirthDate = new DateTime(2004, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(9421),
                            BossId = 1,
                            EmploymentDate = new DateTime(2019, 2, 24, 22, 31, 3, 786, DateTimeKind.Local).AddTicks(9431),
                            FirstName = "Gregoria",
                            HomeAddress = "41356 Runolfsson Rest",
                            LastName = "Shields",
                            LocationId = 19,
                            RoleId = 1,
                            Salary = 2466
                        },
                        new
                        {
                            Id = 34,
                            BirthDate = new DateTime(1967, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(1296),
                            BossId = 2,
                            EmploymentDate = new DateTime(2022, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(1306),
                            FirstName = "Kiera",
                            HomeAddress = "31308 Ansel Divide",
                            LastName = "Hagenes",
                            LocationId = 12,
                            RoleId = 2,
                            Salary = 2504
                        },
                        new
                        {
                            Id = 35,
                            BirthDate = new DateTime(1984, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(2489),
                            BossId = 1,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(2498),
                            FirstName = "Chandler",
                            HomeAddress = "08583 Abbott Ferry",
                            LastName = "Bergstrom",
                            LocationId = 10,
                            RoleId = 4,
                            Salary = 1579
                        },
                        new
                        {
                            Id = 36,
                            BirthDate = new DateTime(1991, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(4410),
                            BossId = 4,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(4420),
                            FirstName = "Celia",
                            HomeAddress = "7484 Makayla Crossroad",
                            LastName = "Kozey",
                            LocationId = 17,
                            RoleId = 2,
                            Salary = 2423
                        },
                        new
                        {
                            Id = 37,
                            BirthDate = new DateTime(1997, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(5638),
                            BossId = 1,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(5648),
                            FirstName = "Kariane",
                            HomeAddress = "95217 Prohaska Garden",
                            LastName = "Connelly",
                            LocationId = 5,
                            RoleId = 1,
                            Salary = 1759
                        },
                        new
                        {
                            Id = 38,
                            BirthDate = new DateTime(1977, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(6861),
                            BossId = 1,
                            EmploymentDate = new DateTime(2003, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(6870),
                            FirstName = "Maria",
                            HomeAddress = "362 Baumbach Club",
                            LastName = "Kovacek",
                            LocationId = 8,
                            RoleId = 3,
                            Salary = 1041
                        },
                        new
                        {
                            Id = 39,
                            BirthDate = new DateTime(1968, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(8077),
                            BossId = 1,
                            EmploymentDate = new DateTime(2004, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(8086),
                            FirstName = "Janie",
                            HomeAddress = "73066 McLaughlin Turnpike",
                            LastName = "VonRueden",
                            LocationId = 5,
                            RoleId = 5,
                            Salary = 2419
                        },
                        new
                        {
                            Id = 40,
                            BirthDate = new DateTime(1988, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(9361),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 787, DateTimeKind.Local).AddTicks(9370),
                            FirstName = "Lexi",
                            HomeAddress = "3678 Herman Walk",
                            LastName = "Jast",
                            LocationId = 1,
                            RoleId = 3,
                            Salary = 1441
                        },
                        new
                        {
                            Id = 41,
                            BirthDate = new DateTime(1956, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(1272),
                            BossId = 5,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(1281),
                            FirstName = "Guido",
                            HomeAddress = "17096 Wade Mews",
                            LastName = "Terry",
                            LocationId = 7,
                            RoleId = 4,
                            Salary = 1903
                        },
                        new
                        {
                            Id = 42,
                            BirthDate = new DateTime(1997, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(2473),
                            BossId = 4,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(2482),
                            FirstName = "Rowan",
                            HomeAddress = "11661 Lueilwitz Divide",
                            LastName = "O'Keefe",
                            LocationId = 11,
                            RoleId = 1,
                            Salary = 2333
                        },
                        new
                        {
                            Id = 43,
                            BirthDate = new DateTime(1990, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(3686),
                            BossId = 4,
                            EmploymentDate = new DateTime(2012, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(3696),
                            FirstName = "Sammie",
                            HomeAddress = "597 Leannon Mountain",
                            LastName = "Bergstrom",
                            LocationId = 12,
                            RoleId = 1,
                            Salary = 1098
                        },
                        new
                        {
                            Id = 44,
                            BirthDate = new DateTime(1957, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(4901),
                            BossId = 3,
                            EmploymentDate = new DateTime(2002, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(4910),
                            FirstName = "Christ",
                            HomeAddress = "124 Kuhlman Row",
                            LastName = "Ruecker",
                            LocationId = 19,
                            RoleId = 4,
                            Salary = 2689
                        },
                        new
                        {
                            Id = 45,
                            BirthDate = new DateTime(1961, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(6239),
                            BossId = 1,
                            EmploymentDate = new DateTime(2015, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(6249),
                            FirstName = "Connie",
                            HomeAddress = "3569 Raynor Streets",
                            LastName = "Gorczany",
                            LocationId = 13,
                            RoleId = 5,
                            Salary = 1224
                        },
                        new
                        {
                            Id = 46,
                            BirthDate = new DateTime(1997, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(7531),
                            BossId = 3,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(7540),
                            FirstName = "Desmond",
                            HomeAddress = "335 Hamill Squares",
                            LastName = "Schulist",
                            LocationId = 8,
                            RoleId = 5,
                            Salary = 2664
                        },
                        new
                        {
                            Id = 47,
                            BirthDate = new DateTime(1965, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(8747),
                            BossId = 4,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(8756),
                            FirstName = "Norberto",
                            HomeAddress = "91315 Powlowski Orchard",
                            LastName = "Larson",
                            LocationId = 19,
                            RoleId = 4,
                            Salary = 1748
                        },
                        new
                        {
                            Id = 48,
                            BirthDate = new DateTime(1969, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(9963),
                            BossId = 2,
                            EmploymentDate = new DateTime(2020, 2, 24, 22, 31, 3, 788, DateTimeKind.Local).AddTicks(9972),
                            FirstName = "Zetta",
                            HomeAddress = "106 Kozey Tunnel",
                            LastName = "Bergnaum",
                            LocationId = 14,
                            RoleId = 3,
                            Salary = 2827
                        },
                        new
                        {
                            Id = 49,
                            BirthDate = new DateTime(1993, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(1188),
                            BossId = 2,
                            EmploymentDate = new DateTime(2019, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(1198),
                            FirstName = "Allan",
                            HomeAddress = "6014 Huels Bridge",
                            LastName = "Purdy",
                            LocationId = 12,
                            RoleId = 1,
                            Salary = 2084
                        },
                        new
                        {
                            Id = 50,
                            BirthDate = new DateTime(1990, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(2509),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(2519),
                            FirstName = "Joanie",
                            HomeAddress = "4990 Harber Shoals",
                            LastName = "Upton",
                            LocationId = 3,
                            RoleId = 2,
                            Salary = 2209
                        },
                        new
                        {
                            Id = 51,
                            BirthDate = new DateTime(1975, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(4573),
                            BossId = 5,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(4582),
                            FirstName = "Mitchel",
                            HomeAddress = "26064 Anya Shoal",
                            LastName = "Gulgowski",
                            LocationId = 10,
                            RoleId = 3,
                            Salary = 2319
                        },
                        new
                        {
                            Id = 52,
                            BirthDate = new DateTime(1990, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(5807),
                            BossId = 4,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(5816),
                            FirstName = "Dave",
                            HomeAddress = "054 Effertz Parks",
                            LastName = "Schroeder",
                            LocationId = 2,
                            RoleId = 3,
                            Salary = 2883
                        },
                        new
                        {
                            Id = 53,
                            BirthDate = new DateTime(1989, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(7037),
                            BossId = 4,
                            EmploymentDate = new DateTime(2002, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(7047),
                            FirstName = "Nels",
                            HomeAddress = "263 Cummings Ports",
                            LastName = "Pagac",
                            LocationId = 15,
                            RoleId = 4,
                            Salary = 2227
                        },
                        new
                        {
                            Id = 54,
                            BirthDate = new DateTime(1972, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(8282),
                            BossId = 5,
                            EmploymentDate = new DateTime(2001, 2, 24, 22, 31, 3, 789, DateTimeKind.Local).AddTicks(8291),
                            FirstName = "Stacy",
                            HomeAddress = "84519 Klein Rapids",
                            LastName = "Kub",
                            LocationId = 6,
                            RoleId = 3,
                            Salary = 2358
                        },
                        new
                        {
                            Id = 55,
                            BirthDate = new DateTime(1962, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(354),
                            BossId = 3,
                            EmploymentDate = new DateTime(2013, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(363),
                            FirstName = "Sam",
                            HomeAddress = "966 Aaron Ranch",
                            LastName = "Kutch",
                            LocationId = 8,
                            RoleId = 2,
                            Salary = 1318
                        },
                        new
                        {
                            Id = 56,
                            BirthDate = new DateTime(1991, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(2443),
                            BossId = 5,
                            EmploymentDate = new DateTime(2013, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(2452),
                            FirstName = "Gilberto",
                            HomeAddress = "61156 Johathan Drives",
                            LastName = "Konopelski",
                            LocationId = 6,
                            RoleId = 3,
                            Salary = 2857
                        },
                        new
                        {
                            Id = 57,
                            BirthDate = new DateTime(1963, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(3791),
                            BossId = 1,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(3801),
                            FirstName = "Reyes",
                            HomeAddress = "2903 Feil Roads",
                            LastName = "Morissette",
                            LocationId = 14,
                            RoleId = 1,
                            Salary = 1999
                        },
                        new
                        {
                            Id = 58,
                            BirthDate = new DateTime(1971, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(5025),
                            BossId = 4,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(5034),
                            FirstName = "Hollie",
                            HomeAddress = "45330 Beier Valley",
                            LastName = "Thiel",
                            LocationId = 3,
                            RoleId = 4,
                            Salary = 1690
                        },
                        new
                        {
                            Id = 59,
                            BirthDate = new DateTime(1980, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(6226),
                            BossId = 5,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(6236),
                            FirstName = "Karolann",
                            HomeAddress = "3509 Runolfsdottir Cove",
                            LastName = "Hyatt",
                            LocationId = 1,
                            RoleId = 5,
                            Salary = 2553
                        },
                        new
                        {
                            Id = 60,
                            BirthDate = new DateTime(1965, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(8284),
                            BossId = 1,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 790, DateTimeKind.Local).AddTicks(8294),
                            FirstName = "Kelvin",
                            HomeAddress = "71041 Arianna Fields",
                            LastName = "Harvey",
                            LocationId = 16,
                            RoleId = 3,
                            Salary = 1723
                        },
                        new
                        {
                            Id = 61,
                            BirthDate = new DateTime(1992, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(464),
                            BossId = 2,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(473),
                            FirstName = "Anastacio",
                            HomeAddress = "803 Bria Grove",
                            LastName = "Nikolaus",
                            LocationId = 7,
                            RoleId = 1,
                            Salary = 2393
                        },
                        new
                        {
                            Id = 62,
                            BirthDate = new DateTime(1994, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(1843),
                            BossId = 4,
                            EmploymentDate = new DateTime(2021, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(1853),
                            FirstName = "Everardo",
                            HomeAddress = "910 Conn Route",
                            LastName = "McClure",
                            LocationId = 7,
                            RoleId = 2,
                            Salary = 1284
                        },
                        new
                        {
                            Id = 63,
                            BirthDate = new DateTime(1984, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(3715),
                            BossId = 2,
                            EmploymentDate = new DateTime(2009, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(3724),
                            FirstName = "Joanie",
                            HomeAddress = "4842 Meggie Circles",
                            LastName = "Goyette",
                            LocationId = 1,
                            RoleId = 5,
                            Salary = 2123
                        },
                        new
                        {
                            Id = 64,
                            BirthDate = new DateTime(1971, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(5727),
                            BossId = 5,
                            EmploymentDate = new DateTime(2015, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(5737),
                            FirstName = "Ivah",
                            HomeAddress = "6100 Myrtie Corners",
                            LastName = "Labadie",
                            LocationId = 2,
                            RoleId = 3,
                            Salary = 1245
                        },
                        new
                        {
                            Id = 65,
                            BirthDate = new DateTime(1969, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(7820),
                            BossId = 4,
                            EmploymentDate = new DateTime(2013, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(7830),
                            FirstName = "Kaylee",
                            HomeAddress = "8974 Anderson Drive",
                            LastName = "Rippin",
                            LocationId = 7,
                            RoleId = 4,
                            Salary = 1148
                        },
                        new
                        {
                            Id = 66,
                            BirthDate = new DateTime(1971, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(9709),
                            BossId = 5,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 791, DateTimeKind.Local).AddTicks(9718),
                            FirstName = "Sam",
                            HomeAddress = "3656 Douglas Corners",
                            LastName = "Harvey",
                            LocationId = 2,
                            RoleId = 1,
                            Salary = 2431
                        },
                        new
                        {
                            Id = 67,
                            BirthDate = new DateTime(1976, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(1656),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(1665),
                            FirstName = "Lyda",
                            HomeAddress = "8472 Bud Ridge",
                            LastName = "Toy",
                            LocationId = 13,
                            RoleId = 5,
                            Salary = 1756
                        },
                        new
                        {
                            Id = 68,
                            BirthDate = new DateTime(2003, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(3677),
                            BossId = 5,
                            EmploymentDate = new DateTime(2019, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(3686),
                            FirstName = "Furman",
                            HomeAddress = "8584 Asia Port",
                            LastName = "Doyle",
                            LocationId = 11,
                            RoleId = 3,
                            Salary = 2606
                        },
                        new
                        {
                            Id = 69,
                            BirthDate = new DateTime(1977, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(5609),
                            BossId = 3,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(5619),
                            FirstName = "Cullen",
                            HomeAddress = "658 Uriah Junctions",
                            LastName = "Fay",
                            LocationId = 16,
                            RoleId = 2,
                            Salary = 1824
                        },
                        new
                        {
                            Id = 70,
                            BirthDate = new DateTime(1978, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(7431),
                            BossId = 4,
                            EmploymentDate = new DateTime(2015, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(7440),
                            FirstName = "Cordia",
                            HomeAddress = "21785 Katheryn Isle",
                            LastName = "Paucek",
                            LocationId = 9,
                            RoleId = 3,
                            Salary = 1085
                        },
                        new
                        {
                            Id = 71,
                            BirthDate = new DateTime(1960, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(8621),
                            BossId = 4,
                            EmploymentDate = new DateTime(2002, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(8630),
                            FirstName = "Cristian",
                            HomeAddress = "800 Kunze Port",
                            LastName = "Crona",
                            LocationId = 10,
                            RoleId = 2,
                            Salary = 2456
                        },
                        new
                        {
                            Id = 72,
                            BirthDate = new DateTime(1999, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(9801),
                            BossId = 5,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 792, DateTimeKind.Local).AddTicks(9810),
                            FirstName = "Vanessa",
                            HomeAddress = "9293 Gorczany Ways",
                            LastName = "Gaylord",
                            LocationId = 15,
                            RoleId = 4,
                            Salary = 1570
                        },
                        new
                        {
                            Id = 73,
                            BirthDate = new DateTime(2000, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(1761),
                            BossId = 3,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(1770),
                            FirstName = "Lizeth",
                            HomeAddress = "5804 Maegan Plains",
                            LastName = "Pfeffer",
                            LocationId = 15,
                            RoleId = 2,
                            Salary = 1053
                        },
                        new
                        {
                            Id = 74,
                            BirthDate = new DateTime(1961, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(3585),
                            BossId = 3,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(3595),
                            FirstName = "Raoul",
                            HomeAddress = "4503 Kali Orchard",
                            LastName = "Keeling",
                            LocationId = 5,
                            RoleId = 2,
                            Salary = 2129
                        },
                        new
                        {
                            Id = 75,
                            BirthDate = new DateTime(1997, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(4780),
                            BossId = 1,
                            EmploymentDate = new DateTime(2020, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(4790),
                            FirstName = "Halle",
                            HomeAddress = "614 Turner Flat",
                            LastName = "Botsford",
                            LocationId = 10,
                            RoleId = 3,
                            Salary = 2391
                        },
                        new
                        {
                            Id = 76,
                            BirthDate = new DateTime(1972, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(6655),
                            BossId = 2,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(6664),
                            FirstName = "Emilia",
                            HomeAddress = "829 Angie Rapids",
                            LastName = "Bosco",
                            LocationId = 15,
                            RoleId = 1,
                            Salary = 2080
                        },
                        new
                        {
                            Id = 77,
                            BirthDate = new DateTime(1983, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(7850),
                            BossId = 2,
                            EmploymentDate = new DateTime(2006, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(7859),
                            FirstName = "Maurine",
                            HomeAddress = "6255 Connelly Harbor",
                            LastName = "Lemke",
                            LocationId = 2,
                            RoleId = 3,
                            Salary = 2726
                        },
                        new
                        {
                            Id = 78,
                            BirthDate = new DateTime(1984, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(9017),
                            BossId = 1,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 793, DateTimeKind.Local).AddTicks(9026),
                            FirstName = "Favian",
                            HomeAddress = "0317 Braun Track",
                            LastName = "Corkery",
                            LocationId = 3,
                            RoleId = 3,
                            Salary = 1131
                        },
                        new
                        {
                            Id = 79,
                            BirthDate = new DateTime(1974, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(225),
                            BossId = 3,
                            EmploymentDate = new DateTime(2018, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(235),
                            FirstName = "Jessyca",
                            HomeAddress = "8957 Hintz Field",
                            LastName = "Stark",
                            LocationId = 16,
                            RoleId = 2,
                            Salary = 2023
                        },
                        new
                        {
                            Id = 80,
                            BirthDate = new DateTime(1999, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(1388),
                            BossId = 5,
                            EmploymentDate = new DateTime(2007, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(1397),
                            FirstName = "Bret",
                            HomeAddress = "949 Schultz Divide",
                            LastName = "Fritsch",
                            LocationId = 20,
                            RoleId = 2,
                            Salary = 2844
                        },
                        new
                        {
                            Id = 81,
                            BirthDate = new DateTime(1990, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(2566),
                            BossId = 5,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(2575),
                            FirstName = "Baby",
                            HomeAddress = "3940 Prohaska Drive",
                            LastName = "Friesen",
                            LocationId = 5,
                            RoleId = 4,
                            Salary = 1204
                        },
                        new
                        {
                            Id = 82,
                            BirthDate = new DateTime(1989, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(4381),
                            BossId = 2,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(4390),
                            FirstName = "Rudy",
                            HomeAddress = "299 Murphy Motorway",
                            LastName = "Funk",
                            LocationId = 18,
                            RoleId = 1,
                            Salary = 1700
                        },
                        new
                        {
                            Id = 83,
                            BirthDate = new DateTime(1963, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(6186),
                            BossId = 5,
                            EmploymentDate = new DateTime(2007, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(6195),
                            FirstName = "Braulio",
                            HomeAddress = "63656 Calista Inlet",
                            LastName = "Wilderman",
                            LocationId = 4,
                            RoleId = 2,
                            Salary = 2970
                        },
                        new
                        {
                            Id = 84,
                            BirthDate = new DateTime(1959, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(8003),
                            BossId = 4,
                            EmploymentDate = new DateTime(2020, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(8012),
                            FirstName = "Khalil",
                            HomeAddress = "564 Kiel Mill",
                            LastName = "Metz",
                            LocationId = 1,
                            RoleId = 4,
                            Salary = 1395
                        },
                        new
                        {
                            Id = 85,
                            BirthDate = new DateTime(1994, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(9840),
                            BossId = 4,
                            EmploymentDate = new DateTime(2011, 2, 24, 22, 31, 3, 794, DateTimeKind.Local).AddTicks(9849),
                            FirstName = "Dagmar",
                            HomeAddress = "58416 Johnathan Neck",
                            LastName = "Kshlerin",
                            LocationId = 7,
                            RoleId = 4,
                            Salary = 2941
                        },
                        new
                        {
                            Id = 86,
                            BirthDate = new DateTime(2003, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(1031),
                            BossId = 1,
                            EmploymentDate = new DateTime(2004, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(1040),
                            FirstName = "Ransom",
                            HomeAddress = "7301 Schulist Rue",
                            LastName = "Spencer",
                            LocationId = 12,
                            RoleId = 2,
                            Salary = 1416
                        },
                        new
                        {
                            Id = 87,
                            BirthDate = new DateTime(2001, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(2201),
                            BossId = 3,
                            EmploymentDate = new DateTime(2013, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(2209),
                            FirstName = "Troy",
                            HomeAddress = "1977 Balistreri Radial",
                            LastName = "Considine",
                            LocationId = 12,
                            RoleId = 5,
                            Salary = 2199
                        },
                        new
                        {
                            Id = 88,
                            BirthDate = new DateTime(1969, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(4035),
                            BossId = 5,
                            EmploymentDate = new DateTime(2016, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(4044),
                            FirstName = "Lois",
                            HomeAddress = "24422 Issac Valley",
                            LastName = "Adams",
                            LocationId = 5,
                            RoleId = 3,
                            Salary = 2368
                        },
                        new
                        {
                            Id = 89,
                            BirthDate = new DateTime(1969, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(5858),
                            BossId = 1,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(5867),
                            FirstName = "Zoe",
                            HomeAddress = "3831 Ethelyn Glen",
                            LastName = "Reichert",
                            LocationId = 7,
                            RoleId = 1,
                            Salary = 2663
                        },
                        new
                        {
                            Id = 90,
                            BirthDate = new DateTime(1955, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(7743),
                            BossId = 1,
                            EmploymentDate = new DateTime(2008, 2, 24, 22, 31, 3, 795, DateTimeKind.Local).AddTicks(7785),
                            FirstName = "Daren",
                            HomeAddress = "3206 Homenick Pike",
                            LastName = "Grimes",
                            LocationId = 9,
                            RoleId = 1,
                            Salary = 1516
                        },
                        new
                        {
                            Id = 91,
                            BirthDate = new DateTime(1965, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(415),
                            BossId = 4,
                            EmploymentDate = new DateTime(2019, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(431),
                            FirstName = "Kayla",
                            HomeAddress = "372 Nico Drive",
                            LastName = "Dare",
                            LocationId = 9,
                            RoleId = 5,
                            Salary = 2164
                        },
                        new
                        {
                            Id = 92,
                            BirthDate = new DateTime(1993, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(2704),
                            BossId = 3,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(2716),
                            FirstName = "Taurean",
                            HomeAddress = "882 Francis View",
                            LastName = "Maggio",
                            LocationId = 6,
                            RoleId = 4,
                            Salary = 1270
                        },
                        new
                        {
                            Id = 93,
                            BirthDate = new DateTime(1963, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(4203),
                            BossId = 1,
                            EmploymentDate = new DateTime(2022, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(4216),
                            FirstName = "Chloe",
                            HomeAddress = "832 Padberg Harbor",
                            LastName = "Brakus",
                            LocationId = 13,
                            RoleId = 4,
                            Salary = 1373
                        },
                        new
                        {
                            Id = 94,
                            BirthDate = new DateTime(1998, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(5689),
                            BossId = 3,
                            EmploymentDate = new DateTime(2005, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(5701),
                            FirstName = "Kaycee",
                            HomeAddress = "38384 Mueller Tunnel",
                            LastName = "Sauer",
                            LocationId = 15,
                            RoleId = 5,
                            Salary = 1889
                        },
                        new
                        {
                            Id = 95,
                            BirthDate = new DateTime(1990, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(7190),
                            BossId = 4,
                            EmploymentDate = new DateTime(2017, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(7202),
                            FirstName = "Raul",
                            HomeAddress = "9134 Langworth Flat",
                            LastName = "Cremin",
                            LocationId = 16,
                            RoleId = 1,
                            Salary = 2998
                        },
                        new
                        {
                            Id = 96,
                            BirthDate = new DateTime(1976, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(9072),
                            BossId = 2,
                            EmploymentDate = new DateTime(2016, 2, 24, 22, 31, 3, 796, DateTimeKind.Local).AddTicks(9082),
                            FirstName = "Quinten",
                            HomeAddress = "76098 Therese Turnpike",
                            LastName = "Breitenberg",
                            LocationId = 20,
                            RoleId = 3,
                            Salary = 2930
                        },
                        new
                        {
                            Id = 97,
                            BirthDate = new DateTime(1976, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(286),
                            BossId = 5,
                            EmploymentDate = new DateTime(2004, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(296),
                            FirstName = "Keeley",
                            HomeAddress = "5491 Waters Island",
                            LastName = "Jast",
                            LocationId = 18,
                            RoleId = 1,
                            Salary = 1685
                        },
                        new
                        {
                            Id = 98,
                            BirthDate = new DateTime(2001, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(1490),
                            BossId = 4,
                            EmploymentDate = new DateTime(2010, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(1499),
                            FirstName = "Amina",
                            HomeAddress = "7274 Steuber Station",
                            LastName = "Mueller",
                            LocationId = 17,
                            RoleId = 5,
                            Salary = 1636
                        },
                        new
                        {
                            Id = 99,
                            BirthDate = new DateTime(1971, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(3347),
                            BossId = 1,
                            EmploymentDate = new DateTime(2007, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(3356),
                            FirstName = "Carlie",
                            HomeAddress = "587 Declan Skyway",
                            LastName = "Leuschke",
                            LocationId = 14,
                            RoleId = 2,
                            Salary = 2415
                        },
                        new
                        {
                            Id = 100,
                            BirthDate = new DateTime(1974, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(4552),
                            BossId = 2,
                            EmploymentDate = new DateTime(2014, 2, 24, 22, 31, 3, 797, DateTimeKind.Local).AddTicks(4562),
                            FirstName = "Lionel",
                            HomeAddress = "9815 Kunde Ramp",
                            LastName = "Johnston",
                            LocationId = 18,
                            RoleId = 4,
                            Salary = 1803
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxAllocation")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Kuhic Radial, New Emeraldstad, Guam",
                            MaxAllocation = 9,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Langosh Row, West Coralie, Egypt",
                            MaxAllocation = 7,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Cecil Islands, East Kaelaborough, Denmark",
                            MaxAllocation = 31,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Gussie Grove, West Celine, Australia",
                            MaxAllocation = 25,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Kayden Manors, South Lianamouth, Malta",
                            MaxAllocation = 48,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Adriel Heights, Medhurstview, Kenya",
                            MaxAllocation = 14,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Albin Prairie, Kurtburgh, Armenia",
                            MaxAllocation = 32,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Noemi Coves, North Yasmeen, Romania",
                            MaxAllocation = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Terrence Brooks, West Oceane, Guernsey",
                            MaxAllocation = 18,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Leffler Square, Emmafort, Madagascar",
                            MaxAllocation = 5,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Henri Dale, Jerdeburgh, South Africa",
                            MaxAllocation = 36,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Corene Forks, Katharinaland, British Virgin Islands",
                            MaxAllocation = 8,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 13,
                            Address = "McDermott Meadows, Candidofurt, Mozambique",
                            MaxAllocation = 26,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Welch Key, East Narciso, Cocos (Keeling) Islands",
                            MaxAllocation = 30,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Botsford Rapids, Port Alek, Gibraltar",
                            MaxAllocation = 19,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Ahmed Lake, Sammyburgh, Nicaragua",
                            MaxAllocation = 37,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 17,
                            Address = "O'Connell Road, Crookstown, Cuba",
                            MaxAllocation = 24,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Miracle Fork, Port Colleenbury, Isle of Man",
                            MaxAllocation = 43,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Kirk Expressway, Celiaville, Sierra Leone",
                            MaxAllocation = 47,
                            Name = "alias"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Rempel Divide, Martaview, Andorra",
                            MaxAllocation = 15,
                            Name = "alias"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CEO"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior Specialist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Intermediate Specialist"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Junior Specialist"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Entry-level specialist"
                        });
                });

            modelBuilder.Entity("EmployeeMangement.Models.Entities.Employee", b =>
                {
                    b.HasOne("EmployeeMangement.Models.Entities.Boss", "Boss")
                        .WithMany("Employees")
                        .HasForeignKey("BossId");

                    b.HasOne("EmployeeMangement.Models.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmployeeMangement.Models.Entities.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
